# Banking legislation: Acts, regulations, guidelines and directives

## Bank and Financial Institution Act, 2073 (2017)

Date of authentication: 2073/01/10 BS (April 23, 2017 AD)

**Chapter-1**: Preliminary

- This Act may be called as "Banks and Financial Institutions Act, 2073 (2017)."
- This Act shall extend to the whole territory of the state of Nepal and also enforce to a branch or liaison office opened outside of Nepal by a bank and financial institution incorporated in Nepal.
- This Act shall come into force at once.

Definitions: In this Act, unless the subject or the context otherwise requires,

- "Court" means a Commercial Bench of the Court designated by the Government of Nepal with the approval of the Supreme Court by a notification published in the Nepal Gazette.
- "Chairperson" means and includes the Chairperson of the Board of Directors and the Executive Chairperson.
- "License" means a license issued by the Rastra Bank in the name of a bank or financial institution to carry out banking and financial transactions, pursuant to this Act.
- "Licensed transaction" means banking and financial transactions to be carried out by a bank or financial institution by obtaining a license under this Act.
- "Licensed Institution" means a bank or financial institution which has obtained a license pursuant to this Act for carrying out banking or financial transaction.
- "Significant Ownership" means a situation where any person has, solely or jointly in association with any other individual or institution, subscribed two percent or more shares of a bank or financial institution and due to share ownership one may have influence on the management of the bank or financial institution.
- "Borrower" means an individual, a firm, company or institution obtained credit from bank or financial institution.
- "Credit" means, and includes any amount lent by a bank or financial institution to any individual, firm, company, institution or other business enterprise subject to the repayment of there on principal, interest or other charge within the certain time limit, direct or indirect gurantee, interest or other charge of the credit, re-finance, restructuring and renewal of the credit, guarantee given and other commitment made for the repayment of such credit and also any type of credit as specified by the Rastra Bank by publishing a public notice.
- "Chief Executive" means, and includes the Chief Executive Officer having responsibility of operating a bank or financial institution and also the Executive Chairperson and Managing Director acting as the Chief Executive.
- "Office" means, the registered and central office of a bank or financial institution and also includes any branch office of a bank or financial institution located within Nepal and outside Nepal and a branch office of a foreign bank or financial institution located in Nepal.
- "Net worth" means any amount that remains after deducting the external liabilities from the grand total of the assets to be maintained in the balance-sheet of a bank or financial institution.
- "Non-executive Director" means a Director excluding the Executive Director performing daily business of a bank or financial institution.
- "Current account" means an account of funds deposited with a bank or financial institution by a costumer that may be withdrawn at any time on demand.
- "Paid-up Capital" means the portion of the capital paid up on behalf of shareholders out of the issued capital of a bank or financial institution.
- "Risk-weight asset" means the total assets calculated by multiplying the amounts coming under each heading of on-balance sheet and off-balance sheet operations of a bank or financial institution by the risk-weight in the format as prescribed by the Rastra Bank.
- "Liquid assets" means the cash balance of a bank or financial institution, the balance remained in the current account, the balance maintained in the Rastra Bank and such assets of a bank or financial institution specified as liquid assets by the Rastra Bank from time to time.
- "Prescribed" or "as prescribed" means prescribed or as prescribed in the Rules or
Byelaws framed under this Act.
- "Securities" means and includes a share, stock, bond, debenture, debenture stock or a mutual investment scheme certificate issued by a bank, financial institution or corporate body or a certificate, saving bond or bond issued by the Government of Nepal or by a corporate body against the guarantee of the Government of Nepal, and also other stock specified by the Securities Board as the stock to be transacted or transferrable through the stock market to sell or exchange such stock.
- "Articles of Association" means the Articles of Association of a bank or financial
institution framed pursuant to the prevailing laws relating to companies.
- "Deposits" means and includes amounts deposited in current, savings or fixed accounts of a bank or financial institution through costumers with or without accruing interests and also such amounts which a bank or financial institution accepts through different financial instruments as specified by the Rastra Bank from time to time.
- "Deposit Guarantee" means the act of security of deposit and guarantee of such deposit pursuant to Section 108.
- "Office bearer" means a Director, Chief Executive, Company Secretary and an officer level employee of a bank or financial institution who is authorized to make a decision on any matter.
- "Family" means a Director's husband or wife, son, daughter-in-law, daughter, adopted sun, adopted daughter, father, mother, stepmother and also the elder brother, elder sister-in-law, younger brother, younger sister-in-law, elder sister and younger sister of the Director, who are dependent on him or her: Provided that the term does not include members of the family being separated after the partition of the family property and carrying out his/her profession or business on his/her own.
- "Capital" means the authorized capital, issued capital and paid up capital of a bank or financial institution.
- "Capital Fund" means and includes the total sum of primary capital and supplementary capital of a bank or financial institution as specified by the Rastra Bank and also any other fund or amount as specified by the Rastra Bank from time to time.
- "Infrastructure Development Bank" means the Infrastructure Development Bank incorporated to carry out financial transactions as referred to in sub-section (5) of section 49.
- "Letter of credit" means a letter written by one bank or financial institution in the name of any other bank or financial institution authorizing the latter thereon to accept cheques, drafts, or bills of exchange of any specified person within the limit of the amount specified therein.
- "Memorandum of Association" means the Memorandum of Association of a bank or financial institution framed pursuant to the prevailing companies' law. 
- "Primary Capital" means and includes the funds of a bank or financial institution listed under such headings as the paid-up capital, share premium, non-redeemable preference shares, general reserve fund and accumulated profit and loss, and also such other funds listed under other headings as may be prescribed as primary capital by the Rastra Bank from time to time.
- "Acquiring Institution" means the holding bank or financial institution acquiring an institution licensed pursuant to this Act.
- "Acquisition" means the act of acquisition by a licensed institution to another licensed institution having settled the accounts of entire assets and potential liabilities by winding up the legal capacity of such institution and also the act of accepting all contractual liabilities by the acquiring bank or financial institution created by the targeted institution before its merger.
- "Savings Account" means accounts containing details of the amounts deposited by any customer for savings in a bank or financial institution.
- "Bank" means and includes corporate body incorporated to carry out banking and financial transactions as referred to in Sub-Section (1) of Section 49 and a branch office of a foreign bank located in Nepal, a branch office opened outside of Nepal by a bank incorporated in Nepal and an Infrastructure Development Bank to performing the functions as referred to the Section 49 and a branch office of the same bank.
- "Banking and financial transaction" means the banking and financial transaction as referred in Section 49.
- "Bonus share" means and includes share issued as an additional share to shareholders, by capitalizing the saving earned from the profits or the reserve fund of a bank or financial institution, and the increase of the paid up amount of a share by capitalizing the saving or other fund.
- "Fixed Account" means a periodic account of funds deposited with a bank or financial institution for a specified term , during which normally the deposited amount cannot be withdrawn.
- "Rastra Bank Act" means the Nepal Rastra Bank Act, 2058 (2002).
- "Rastra Bank" means the Nepal Rastra Bank.
- "Targeted Institution" means a bank or financial institution to be merged in an acquiring institution pursuant to this Act with entire assets and liabilities.
- "Audit Committee" means the Audit Committee as referred to in section 60.
- "Dividend" means cash dividend, interim dividend or bonus share to be given by a bank or financial institution according to this Act and the prevailing laws.
- "Liquidator" means and includes a person appointed for carrying out the functions of liquidation of bank or financial institution according to an order of a court or a resolution adopted by a meeting of the creditors and as well as an office carrying out the function of a liquidator.
- "Leasing" means an act of acquiring only the possessory right of a movable or immovable asset for a specified period of time by retaining the ownership thereof with the bank or financial institution in consideration of which a lessee is required to pay the rent within the schedule as per the agreement.
- "Off-balance-sheet transaction" means and includes letters of credit, letters of guarantee, letters of acceptance, commitments, swaps, options and transaction in advance concerning foreign exchange having, the potential of bearing liabilities by a bank or financial institution and also transactions of the instruments as specified by the Rastra Bank, from time to time.
- "Financial institution" means and includes a corporate body incorporated to carry out banking and financial transactions as referred to in to sub-sections (2), (3) or (4) of Section 49 and a branch office of a development bank, finance company, micro finance institution or a branch office of a foreign financial institution located in Nepal and also a branch office opened abroad by a financial institution incorporated in Nepal.
- "Financial interests" means a situation where any Director, shareholder subscribing one percent or more shares or the Chief Executive or a family member of such a person or the individual, company, or corporate body having the authority to appoint a Director subscribes ten percent or more shares of a firm, company or corporate body separately or jointly, such a person or persons are deemed to have financial interests in the institution having ten percent or more shares, and also include the interests which the Rastra Bank specifies as having financial interests depending upon the nature and circumstance of a financial transaction.
- "Branch of a foreign bank or financial institution" means a branch of any bank or
financial institution having obtained a license from the Rastra Bank in accordance
with this Act to carry out banking and financial transactions having opened a branch
office in Nepal.
- "Electronic transaction" means and includes the business of accepting deposits, making payments and transferring funds through telephone, telex, computers or magnetic tapes or other electronic equipment of a similar nature and transactions to be carried out through terminal, automated teller machines and cash dispensing machines, as well as those to be carried out through charge cards, debit or credit cards.
- "Prospectus" means the prospectus to be published by a bank or financial institution pursuant to Section 8.
- "Branch Office" means any branch, sub-branch, unit, area, and representative or liaison office of a bank or financial institution within and outside Nepal and any office including a branch or representative office or liaison office or any other office of a foreign bank or financial institution in Nepal.
- "Share" means the divided portion of the share capital of a bank or financial institution.
- "Shareholder" means a person having ownership in a share of a bank or financial institution.
- "Director" means and includes a member of the Board of Directors and also the Chairperson of the Board of Directors as well as an Alternate Director. 
- "Board of Directors" means the Board of Directors constituted pursuant Section 14.
- "Promoter" means a person who, having undertaken to subscribe at least one share, signs the Articles of Association and the Memorandum of Association in the capacity of a Promoter for the incorporation of a bank or financial institution pursuant to this Act.
- "Affiliated person" means a Director, office bearer of a bank or financial institution or his/her family member or any firm, company or institution having substantial ownership of such a person or any person, firm, company or institution having substantial ownership in such a firm, company or institution or also a beneficial owner with substantial ownership thereof.
- "Independent Director" means the person appointed to the position of Independent Director pursuant to Sub-Section (3) of Section 14.
- "Voluntary Liquidation" means a situation in which a bank or financial institution initiates voluntary liquidation pursuant to Chapter 11.
- "Creditor" means and includes a person or a body corporate to whom/which a bank or financial institution has to pay and also a depositor and debenture-holder for the purpose of liquidation process.
- "Hypothecation Loan" means a loan disbursed having entered into an agreement between a bank or financial institution and a Borrower against the collateral security of the stock having retained such stock under possession of the borrower concerned.

**Chapter-1**: Provisions Relating to Incorporation of a Bank or a Financial Institution

3. Incorporation of Banks or Financial Institutions:

(1) Any person, wishing to incorporate a bank or financial institution to carry out financial transactions according to this Act shall incorporate it by getting such a bank or financial institution registered as a public limited company in accordance with the prevailing laws: Provided that banks or financial institutions which are in operation at the commencement of this Act do not require to be incorporated pursuant to this sub-Section.
(2) An official authorized in accordance with the prevailing laws in force to register a company pursuant to Sub-Section (1) shall register the company subject to Section 4.

4. Prior-approval to be Obtained to Incorporate Banks or Financial Institutions: 

(1) A person or an institution desires to incorporate a bank or financial institution for the purpose of Section 3 shall, while making an application for getting such a bank or a financial institution registered according to the prevailing laws, make an application to the Rastra Bank along with the prescribed fee for obtaining prior approval having enclosed therewith the following documents:

(a) Memorandum of Association of the proposed bank or financial institution,
(b) Articles of Association of the proposed bank or financial institution,
(c) Feasibility study report of the proposed bank or financial institution,
(d) Personal details of the applicant in the form as prescribed by the Rastra Bank,
(e) A certified copy of the agreement, if any, concluded between the applicants prior to incorporation of the bank or financial institution in relation to incorporation of the bank or financial institution,
(f) Evidence of the statement disclosing the sources of incomes and of tax clearance by the applicants up to the fiscal year immediately preceding the making of the application pursuant to this Section,
(g) Details as to whether or not the applicant of the proposed bank or financial institution has become a bankrupt in Nepal or abroad, whether or not he/she has borrowed any loan from any bank or financial institution, whether or not the person has been blacklisted in any transaction with a bank or financial institution, if so, whether or not a period of three years has lapsed after having such a blacklisting,
(h) Self-declaration of the applicant stating that no action has been taken against and no punishment has been imposed on the applicant in Nepal or abroad for being involved in cheating, fraud or any criminal offence deemed to be as such as per the prevailing laws,
(i) Details as to whether or not any action has been taken against the applicant in Nepal or abroad by any regulatory or oversight authority or whether or not a license of the company or bank or financial institution in which he/she is associated with has been suspended, revoked or subjected to compulsory liquidation or is in the course of being so,
(j) Details as to the names, surnames, addresses and relationship of the family members of the applicant; substantial ownership and capacity of each of them and if any of them is a Director, official or employee in any institution, details as to the title of the post each of them holds: Provided that in cases where a body, applicant is a corporate, details as to the person having substantial ownership or position in that body corporate body, the audited financial statements of the last three years as well as the tax clearance certificate of that corporate body shall also be enclosed.
(k) Written authority given to the Rastra Bank to allow it to conduct or to cause to conduct an inquiry as to the financial and professional background of the applicant and to share such notice and information,
(l) An undertaking that the deposits to the limits as prescribed by the Rastra Bank will be guaranteed,
(m) Other details or documents as specified by the Rastra Bank from time to time.

(2) The Rastra Bank may, if it finds appropriate to grant approval upon the examination of the application submitted for prior approval pursuant to Sub-Section (1) and enclosed documents, grant its approval to incorporate such a bank or financial institution within one hundred twenty days after filing of the application, with or without prescribing any conditions.
(3) Notwithstanding anything contained in Sub-Section (2), no prior approval shall be given to incorporate a bank or financial institution to the following persons and the firms or companies having substantial ownership of such persons and of the members of their family if they had been:

(a) Being investigated in regulatory actions of the Rastra Bank,
(b) Convicted of any banking offence,
(d) Convicted of cheating, fraud, forgery,
(e) Convicted of any offence of money laundering and terrorist financing activities,
(f) Convicted of any the offence of corruption,
(g) Convicted of any serious types of offences such as trafficking-in-person, kidnapping,
(h) Hostage, taking and rape.

5. Prior Approval to be Obtained for Incorporation of Bank or Financial Institution in Foreign Investment: 

(1) A foreign bank or financial institution shall, for the purpose of obtaining prior approval to incorporate a bank or financial institution as a subsidiary company in accordance with this Act in joint venture with a corporate body registered in Nepal or with a Nepali citizen or to maintain the share capital as specified by the Rastra Bank, shall submit in addition to the documents set forth in Sub-Section (1) of Section 4 the following documents and details along with the fee specified by the Rastra Bank:
(a) The Memorandum of Association, Articles of Association of the foreign bank or financial institution and a copy of the certificate of incorporation of the bank or financial institution in the country concerned and capital structure thereof,
(b) A copy of the license of the foreign bank or financial institution obtained from the country concerned for carrying out banking and financial transactions,
(c) Details as to the principal place of business,
(d) A certified copy of the audited balance-sheet and profit and loss account of the last three years of the foreign bank or financial institution,
(e) Details as to the proposed business plan in Nepal, business strategies and types of transaction to be carried out, internal control, and risk management,
(f) Decision made by the foreign bank or financial institution as per the prevailing laws of the country concerned to open bank or financial institution in Nepal and the authority granted by the regulatory body of the country concerned.

(2) The Rastra Bank may, if it deems appropriate to grant approval upon examination of the application submitted for prior approval pursuant to Sub-Section (1) and enclosed documents, grant its approval to a foreign bank or financial institution for incorporation of the bank or financial institution in joint venture or within the prescribed share limit within one hundred twenty days after making of an application, with or without prescribing any conditions.
(3) A foreign bank or financial institution may, with approval from the Rastra Bank, take share ownership of a local bank or financial institution having been in operation, as a joint venture by completing the procedures as prescribed by the Rastra Bank.
(4) Notwithstanding anything contained elsewhere in this Act, investment made by any foreign bank or financial institution or other foreign institution by getting approval pursuant to the prevailing laws before the commencement of this Act shall be deemed to have been continued.

6. Approval to be Obtained to Open Branch Office of Bank or Financial Institution:

(1) If any internationally rated foreign bank or financial institution wishes to open a branch office to carry out banking and financial transactions or non-banking financial transactions within Nepal, prior approval of the Rastra Bank shall be obtained before opening such a branch office.
(2) For the purpose of Sub-Section (1), an application shall be made to the Rastra Bank along with the capital and fees as prescribed by the Rastra Bank.
(3) While making an application pursuant to Sub-Section (2), such a foreign bank or financial institution shall submit the following details and documents in addition to the details and documents as referred to in Sub-Section (1) of Section 5:
(a) Written commitment made by the Board of Directors that it will make available on demand of the Rastra Bank the amount necessary for fulfilling its entire liabilities with regard to the business activities of its branch or representative or liaison office of the foreign bank or financial institution concerned in Nepal,
(b) Details as to the location of the proposed branch office of the foreign bank or financial institution,
(c) Details as to the possible office bearers in the proposed branch office of the foreign bank or financial institution.

(4) The Rastra Bank may, if it deems necessary to demand further documents or details while carrying out inquiry into the documents or details submitted pursuant to Sub-Section (3), demand the required documents or details from the concerned applicants.
(5) The Rastra Bank may, if it deems appropriate to grant prior approval while carrying out inquiry into additional documents submitted pursuant to Sub-Section (3) and of the documents asked for submission pursuant to Sub-Section (4), grant approval to open a branch office in Nepal within one hundred twenty days after filing of the application, with or without prescribing any conditions.
(6) The foreign bank or financial institution, after obtaining prior approval as referred to in Sub-Section (5), shall register a branch office according to the prevailing companies laws.
(7) The branch office of a foreign bank or financial institution registered pursuant to Sub-Section (6) shall make an application to the Rastra Bank along with the following documents and details as well as the charge or fee as prescribed by the Rastra Bank for approval to carry out banking and financial transactions in Nepal:

(a) Registration certificate registered according to the prevailing laws to carry out baking and financial transactions in Nepal as a branch office,
(c) Letter of approval or consent granted by the Government or Central Bank or regulating agency according to the law of the country concerned of the foreign bank or financial institution to open a branch office of such bank or financial institution in Nepal,
(d) Details of the discrepancy, if any, in any matter to be completed by the foreign bank or financial institution concerned according to this Act after the submission of the application before the Rastra Bank for the establishment of a branch office of the foreign bank or financial institution or after obtaining approval from the Rastra Bank,
(e) Other information and details as may be demanded by the Rastra Bank.

(8) The Rastra Bank may, if it deems appropriate upon carrying out inquiry into the application received pursuant to Sub-Section (7), grant approval to such a branch office of a foreign bank or financial institution for carrying out banking and financial transactions in Nepal, within ninety days from the date of filing the application.
(9) The Rastra Bank may, while granting approval pursuant to Sub-Section (8), prescribe the necessary terms and conditions.
(10) A bank or financial institution may open a branch office outside Nepal by obtaining approval from the Rastra Bank.
(11) The Rastra Bank may, from time to time, make policies as may be required with regard for opening branch office outside of Nepal pursuant to Sub-Section (10).

7. Power to Refuse to Grant Prior Approval: (1) The Rastra Bank may refuse to grant prior approval for the incorporation of any bank or financial institution and for opening a branch office of the foreign bank or financial institution in any of the following circumstances:
(a) If the name of or banking and financial transaction to be carried out by, the proposed bank or financial institution is not found to be appropriate from the point of view of public interest, religions, ethnicities or communities etc.,
(c) If the objectives of the proposed bank or financial institution are contrary to the laws in force,
(d) If incorporation of the proposed bank or financial institution does not seem to be technically appropriate,
(e) If a study of the feasibility study report, details and documents and other infrastructures submitted by the proposed bank or financial institution does not provide a ground to believe that it may carry out financial transactions in a healthy and competitive manner,
(f) If all promoters of the proposed bank or financial institution have not signed the Memorandum of Association and Articles of Association, stating their names, addresses and number of shares subscribed by them, in the presence of a witness and the name and address of the witnesses have not been mentioned,
(g) If per person share investment limit and share ownership ratio has not been found to have been maintained as specified by the Rastra Bank from time to time,
(h) If it is found to be contrary to the policy relating to incorporation of banks or financial institutions and licensing policy issued by the Rastra Bank,
(i) If any condition as prescribed by the Rastra Bank has not been found to be fulfilled.
(2) If the Rastra Bank refuses to grant prior approval to the proposed bank or financial institution for any of the reasons as referred to in Sub-Section (1), information shall be given to the applicant stating the reasons thereof.

**Chapter-3**: Provisions Relating to Transactions of Securities

8. Prospectus
9. Allotment of Shares
10. Transactions of Securities
11. Provisions Relating to the Sale of Shares or Pledging of Securities
12. Prohibition on Transaction of Securities
13. Prohibition on buy back by Bank or Financial Institutions of its' Own Shares.

**Chapter-4**: Provisions Relating to Board of Directors and Chief Executive

14. Constitution of Board of Directors
15. Term of Office of the Directors
16. Qualifications of Director
17. Qualifications of Independent Director
18. Disqualification of Directors
19. Ineligibility to Remain in Office of Director
20. Provision Regarding a Person Holding Constitutional Position
21. Meetings of Board of Directors
22. Functions, Duties and Powers of Board of Directors
23. Responsibility and Accountability of Director
24. Details of Directors to be Collected
25. Information of Director and Record
26. Power to Constitute Sub-Committees
27. Delegation of Power
28. Allowances and Facilities of Director
29. Appointment of Chief Executive and Terms and Conditions of Service
30. Functions, Duties and Powers of Chief Executive

**Chapter-5**: Provisions Relating to Licenses

31. Prohibition on carrying out Banking or Financial Transactions by anyone other than Banks or Financial Institutions
32. Use of Name of Banks or Financial Institutions
33. Application to be Made to Obtain a License for Carrying on Banking and Financial Transactions
34. License may be granted for carrying out Banking and Financial Transactions
35. Power to Refuse to Grant a License
36. Power to Rastra Bank to Specify Conditions
37. Classification of Bank or Financial Institutions
38. Possibility of Being Converted into Higher Class of Bank or Financial Institution
39. List to be Published
40. Special Provisions Relating to Branches of Foreign Banks

**Chapter-6**: Provisions Relating to Capital, Capital Fund and Liquid Assets

41. Capital to be Maintained
42. Capital Fund
43. Provisions Concerning Possible Loss
44. General Reserve Fund
45. Exchange Equalization Fund
46. Liquid Assets to be Maintained
47. Declaration and Distribution of Dividends
48. Power to Issue Order to Decrease Capital

**Chapter-7**: Provisions Relating to Operation of Banking and Financial Transactions

49. Powers of Banks or Financial Institutions to Carry out Banking and Financial Transactions
50. Acts not Allowed to be carried out by Banks or Financial Institutions
51. Provisions concerning Subsidiary Company
52. Prohibition on carrying out transactions with relevant persons
53. Information of Suspicious Transaction to be furnished
54. Rastra Bank to issue Directives

**Chapter-8**: Provisions Relating to Disbursement and Recovery of Credits

55. Provisions Relating to Disbursement of Credits
56. Monitoring as to Utilization of Credit Amount
57. Provisions on Recovery of Credit

**Chapter-9**: Provisions on Accounts, Records, Details and Reporting

58. Accounts to be Maintained Accurately
59. Balance-sheet, Profit and Loss Accounts to be Prepared
60. Audit Committee
61. Functions, Duties and Powers of the Audit Committee
62. Auditing
63. Appointment and Remuneration of Auditor
64. Ineligibility for Appointment as Auditor
65. Details to be Furnished
66. Functions, Duties and Powers of Auditor
67. Recommendation for taking actions against Auditor

**Chapter-10**: Provisions Relating to Merger or Acquisition of Banks or Financial Institutions

69. Banks or Financial Institutions may be Merged or Acquisitioned
70. Application to be submitted for Merger or Acquisition
71. Provisions Concerning Valuation of Assets and Liabilities
72. Provisions Relating Agreement
73. Provisions Relating to Approval
74. Transactions may be Acquired

**Chapter-11**: Voluntary Liquidation of Banks or Financial Institutions

75. Voluntary Liquidation of Bank or Financial Institution
76. Initiation of Voluntary Liquidation
77. No Effect in Liability

**Chapter-12**: Provisions Relating to Mandatory Liquidation of Bank or Financial Institutions

78. Application may be filed before the Court for Mandatory Liquidation of Banks or Financial Institutions
79. Circumstances leading to Mandatory Liquidation of Bank or Financial Institutions
80. Transaction to be Suspended
81. Appointment of Liquidator
82. Functions, Duties and Powers of Liquidator
83. Effects of Order Relating to Liquidation
84. Records of Assets and Liabilities
85. Power to terminate Transactions
86. Notice to submit claims
87. Power of Liquidator to Accept or Reject Claims
88. Classification of Claims
89. Meeting of Creditors
90. Liquidation Plan
91. Advance Payment may be made to Depositors Immediately
92. Power to Sell Assets
93. Notice of Settlement of Claims
94. Order of Priority of Payment
95. Unclaimed Goods or Amount
96. Decision of Liquidation
97. Mandatory Liquidation of Bank or Financial Institution Carrying on Transactions in More than One Country
98. No claim to be entertained

**Chapter-13**: Provisions Regarding Actions, Offenses and Punishment

99. Power to Take Regulatory Actions
100. Power to impose fines
101. Procedures of Actions
102. Control Over Licensee Institutions
103. Offenses
104. Punishment
105. Appeal
106. No Difficulty in Imposing Punishment

**Chapter-14**: Miscellaneous

107. Special Provisions Relating to Infrastructure Development Bank
108. Security of Deposits to be made
109. Banking Secrecy to be Maintained
110. Power to Give Directive to Freeze Accounts
111. Right to Make Claims Over the Deposits
112. Statement of Unclaimed Deposits
113. Recovery from or confiscation of deposits
114. Recovery from Director
115. Prohibition of Making Claims
116. Government of Nepal to be Plaintiff
117. Provisions Relating to Transparency
118. Provisions Relating to Protection of Customers' Interests
119. Exemption and facilities
120. Expenditure Management
121. Statement of Assets to be Submitted
122. Credit, Liabilities and Titles against the Collateral of Credit may be purchased or sold
123. Settlement of Disputes
124. Not to be liable for acts done in good faith
125. Actions Taken not to be Invalid
126. Study Committee and Sub-committee may be formed
127. Taking Oath of Office
128. Amendment of Memorandum of Association and Articles of Association
129. This Act to Prevail
130. Power to Remove Difficulties
131. Power to issue Order or Direction
132. Power to frame Rules, Bylaws
133. Power to Frame Bylaws and Working Procedures
134. Repeal and Saving

### Changes in BAFIA, 2073 in comparison to BAFIA, 2063

- Replaces previous act (BAFIA, 2063)
- Any person seeking to establish Banks and Financial Institutions ("BFI") henceforth shall be required to register the same as a public company under the provisions of the Company Act. Prior to incorporation of such company, approval from the Central Bank (NRB) must be obtained.
- Requirements for prior approval are:
  - Memorandum of association
  - Articles of association
  - Feasibility study report
  - Personal details of applicant
  - Agreement between applicants for establishment of BFI
  - Tax Clearance Certificate of applicant
  - Details of financial credibility
  - Declaration of any regulatory action taken against applicant or cancellation of license of any related entity
  - Details of family and their profession
  - Authorization of NRB to investigate about the applicant's credentials
  - Pledge to secure specified amount of deposits
  - Other requirements as specified by NRB
- Approval of NRB shall also be required to establish BFI with foreign ownership or to establish branch of foreign BFI.
- Additional requirements for establishment of BFI with foreign ownership.
  - Corporate documents of foreign BFI
  - License of foreign BFI
  - Details of main place of business
  - Audit report for previous 3 fiscal years of foreign BFI
  - Details of plan of business in Nepal
  - Approval of foreign regulatory agency to establish BFI in Nepal
- Any BFI seeking to engage in trading securities shall obtain necessary approval under prevailing law and register its prospectus with the NRB. BFI shall allocate a minimum of 30% of its total issued capital for the public (comprising of natural persons) except in case of BFI established under ownership of GoN. Shares which are allocated for the public but not subscribed within the specified time period may be issued to other entities such as firm, companies, organizations etc. In any case the promoter shareholding group shall always own at least 51% of the shares. Promoter of BFI shall not be allowed to sell or pledge their shares within 5 years of commercial operation.
(Continue from page 555 of the Advanced Banking Knowledge book)

## Nepal Rastra Bank Act, 2058 (2002)

The Nepal Rastra Bank Act, 2002 (amended in 2006) provides for the establishment of Nepal Rastra Bank to function as central bank. The bank is provisioned to be an autonomous and corporate body with perpetual succession, separate seal for transaction of business of the bank, and incorporation alike an individual to acquire, utilize, retain, sell and otherwise dispose property.

It replaces the older act of 2012 BS. This act provides legal authority for the NRB to act as the central bank of Nepal. There are 12 chapters and 112 sections in the act.

**Importance**

- Legal basis for establishment and operation of NRB as the central bank.
- Formulation and implementation of monetary and foreign exchange policies (as per Clause 44, Chapter 5 "Monetary functions and operation of open market" of NRB act, 2002)
- Maintain stability of price

**Strength**

- Provides autonomy to central bank
- Clear provision of Board of Directors (BoD) and governors
- Guidelines to central bank as well as BFIs
- Coordination and smooth relation with GoN.

**Weakness**

- Focus on traditional banking functions
- Does not present as a comprehensive act covering BFIs
- More power endowed to BoD
- No clear provision on faults and punishment
- Influenced by government/finance minister and ministry

**(Section 4) Objectives of the Bank**

- To formulate necessary monetary and foreign exchange policies in order to maintain the stability of price and balance of payment for economic stability and sustainable development of economy, and manage it;
- To increase the access of the financial service and increase the public confidence towards the banking and financial system by maintaining stability of the banking and financial sectors,
- To develop a secure, healthy and efficient system of payment;
- The bank shall extend co-operation in the implementation of the economic policies of Government of Nepal.

**(Section 5) Functions, duties and powers of the Bank**

- To issue bank notes and coins;
- To formulate necessary monetary policies in order to maintain price stability and to implement or cause to implement them;
- To formulate foreign exchange policies and to implement or cause to implement them;
- To determine the system of foreign exchange rate;
- To manage and operate foreign exchange reserve;
- To issue license to commercial banks and financial institutions to carry on banking and financial business and to regulate, inspect, supervise and monitor such transactions;
- To act as a banker, advisor and financial agent of Government of Nepal;
- To act as a banker of commercial banks and financial institutions and to function as the lender of the last resort;
- To establish and promote the system of payment, clearing and settlement and to regulate these activities; and
- To operate open market transaction through necessary instruments for liquidity management;
- To implement or cause to implement any other necessary functions which the Bank has to carry out in order to achieve the objectives of the Bank under this Act;

The bank may carry out the following functions (Subsection 2, Section 7)

- To provide loan to and invest in the shares of the institutions which carry out the functions helpful in carrying out the function of the Bank or in attaining its objectives, not exceeding ten percent of the total capital of such institutions. (explained in the amendment to the Act)
- To provide loan to its own employees.

**(Section 6) Prior Right of the Bank**

- For the purpose of recovering any loan, which the Bank has given to any borrower or any other type of claim of the Bank against any borrower, the Bank shall have prior right of security over cash deposited in an account in the name of such borrower at the Bank or in any commercial bank or financial institution or against any other moveable and immovable property owned by the borrower for the purpose of recovering such loan.
- The Bank shall recover its loan by taking into its custody the cash or movable or immovable property having its prior right and selling such property as prescribed.

**(Section 7) Functions not to be carried out by the Bank**

- Providing any loan, accepting any type of deposit or making any type of financial gift;
- Purchasing shares of any commercial bank, financial institution, public corporation or a company or acquiring any type of proprietary right in any financial, commercial, agricultural, industrial or other institution.
- Carrying out any type of trade; and
- Acquiring right over movable and immovable property by way of purchase, lease or in any manner whatsoever.

**(Section 8) Privilege and facilities of the Bank**

- Exemption from all types of taxes, fees and charges on the income, capital transactions, houses, land, assets, etc.;
- No requirement for the payment of registration fee for registration of the deeds of loan or refinance to be given by the Bank.
- No requirement of revenue stamps on any of the documents relating to the Bank;
- No tax, fee, charge, duty on the export and import of bank notes, coins, gold, silver and the paper, metal, chemicals, and other materials to be used for printing bank notes and minting coins.

**(Section 9)** Relation between the Government of Nepal and the bank, contacts to be made through the Ministry of Finance.

**(Section 10)** Coordination with public bodies; Government may request necessary information on balance of payment, banking and financial matter and upon the request of the Bank to GoN, public and private sector, such segments shall provide necessary economic and financial information.

**(Section 11)** International cooperation and relationship

**(Section 12)** Flow of public information

**(Section 13)** Operation of Accounts

**(Chapter 3, Section 14) Formation of Board**

- There shall be a board of directors in the banks consisting of the following members;
  - Governor $\longrightarrow$ Chairperson
  - Secretary ( Ministry Of Finance) $\longrightarrow$ Member
  - Two deputy governors $\longrightarrow$ Member
  - Three Directors appointed by the government of Nepal from amongst the person renowned in the in fields of Economics, Monitory, Banking, Finance, and commercial law $\longrightarrow$ Member

**(Section 15) Appointment of Governor**

- Government of Nepal, the council of minster shall appoint governor on the basis of the recommendation of recommendation committee formed pursuant a subsection (2)

- Chaired by Governor $\longrightarrow$ Member
- One person among the former governor $\longrightarrow$ Member
- One person designated by the government of Nepal from amongst the person renowned in the in fields of Economics, Monitory, Banking, Finance , and commercial law $\longrightarrow$ Member.

**(Section 16) Appointment of Deputy Governor**

- Government of Nepal, the council of Minister shall appoint Deputy Governor on the recommendation of Governor.
- While making the recommendation for application of Deputy Governor, recommend double the number of the post falling vacant from among the special class officers of the Bank on the basis of their performance and capability.
- The person appointed in the post of Deputy Governor under this Section shall be deemed to have been automatically retired from the service of the Bank.

**(Section 17)** Appointment of the Directors

**(Section 18) Tenure of Office of the Directors**

- The tenure of office of the Governor, Deputy Governor and Directors shall be of 5 years.
- GoN may reappoint the retiring Governor for one term and the retiring Directors for any term, if it is deemed necessary.

**(Section 19)** Remuneration and other benefits to the Directors

**(Section 20)** Qualifications of the Directors

**(Section 23)** Constitution, functions and duties of inquiry committee

**(Section 29) Functions, Duties, and power of Board**

(a) To frame monetary and foreign exchange policies;
(b) To take necessary decisions with regard to the denominations of bank notes and coins, the figures, size, metal, materials for printing notes, and other materials; and to frame appropriate policies with regard to their issue;
(c) To frame necessary policies for causing the supervision and inspection of commercial banks and financial institutions and banking and financial arrangement.
(d) To approve Rules and Bye-laws of the Bank and to frame policies applicable to the operation and management of the Bank;
(e) To frame policies with regard to the appointment, promotion, transfer, dismissal, remuneration, pension, gratuity, provident fund, leave, code of conduct and other terms and conditions relating to the service of the employees of the Bank;
(f) To approve the annual programs and budget of the Bank and the annual auditing of accounts, and to submit its report to Government of Nepal for information;
(g) To approve the annual report on the activities of the Bank;
(h) To frame necessary policy for the issue of license to commercial banks and financial institutions and for revoking such license;
(i) To approve the limit of the loan to be provided to GoN by the Bank;
(j) To fix the amount, limit and terms and conditions of the loan and refinance which the Bank provides to the commercial banks and financial institutions;
(k) To make decision with regard to the Bank's membership to international organizations, associations;
(l) To frame policy for the mobilization and investment of Bank's financial resource;
(m) To submit proposal to Government of Nepal along with the reasons there for if it is necessary to make amendment to this Act;
(n) To take decision on all other matters excluding the matters which are within the authority of Governor under this Act; and
(o) To delegate the powers vested on the Board to the Governor or the subcommittee constituted by the Board with or without fixing the time limit.

**(Section 30) Functions, Duties, and power of the Governor**

- To implement decisions made by the board;
- To operate and manage the bank;
- To systematize the functions to be carried out by the bank;
- To represent the Nepal Rastra Bank in the international platform;
- To implement and cause to implement the policies relating to monetary and foreign exchange matters;
- To formulate necessary policy on rates of interest for deposits and loan with commercial banks and financial institutions;
- To formulate necessary policies with regard to rate of interest to be paid by commercial banks and financial institutions on deposit and loan or the rate of interest to be charged by them on deposits and loan;
- To formulate necessary policies relating to liquidity to be maintained by commercial banks and financial institutions;
- To make necessary arrangement with regard to the basis, amount, methods, conditions and duration of compulsory deposit to be maintained by commercial banks and financial institutions, and its use;
- To fix the terms and conditions relating to adequacy of the capital fund of commercial banks and financial institutions;
- To take decision with regard to the procedures and terms and conditions to be followed while purchasing and selling gold and other precious metals;
- To fix charge on the services to be provided by the Bank;
- To take decision for opening and closing branch offices and other offices of the Bank as may be necessary;
- To establish and close the agency of the Bank;
- To make necessary arrangement for development and operation of information system of Bank;
- To make necessary arrangement for supervision of commercial banks and financial institutions;
- To take decision with regard to revocation of the license provided to commercial banks and financial institutions.
- To take decisions on any other matters subject to the powers delegated by the Board of Directors;

The powers to be exercised by the Governor of a Central Bank in accordance with international practice shall be vested in the Governor.

**(Section 33)** Management committee

**(Section 34) Audit committee**

The government shall constitute an audit committee comprising of the following members

- One director designated by the Board $\longrightarrow$ Coordinator
- One subject expert designated by the Board $\longrightarrow$ Member
- Chief of internal audit department of the bank $\longrightarrow$ Member

**(Section 35) Function, Duties, and power of the audit committee**

- Submit audit report to the NRB board.
- The audit committee can recommend for the preparation of budget and audit procedure, support to prepare a periodic balance sheet and other documents.
- Supervise the implementation of the NRB policies of measures.
- Audit managerial and performance appraisal of the NRB entity.
- Frame bylaws relating to audit under the provision of prevailing law.

**(Section 37)** Professional code of conduct and official responsibility

**(Section 38)** Confidentiality

**(Chapter 4)** Financial provisions

- The capital of the Bank shall be 5 billion rupees. (Section 39)

**(Chapter 5)** Monetary functions and operation of open market

- Monetary policy (Section 44)
- Operation of open market transaction (Section 45)
- Compulsory deposit of commercial banks and financial institutions (Section 46)
- Loan and refinance to commercial banks and financial institutions (Section 49)

**(Chapter 6)** Monetary unit, banknote and coins

**(Chapter 7)** Foreign exchange policy, regulation and reserve

**(Chapter 8, Section 69) Relation with Government of Nepal**

- Bank, advisor and financial agent (Section 69)
- Consultation and information relating to external debt (Section 70)
- Deposit collection (Section 71)
- Functions of fiscal agent (Section 72)
- Bank may ask for Particulars, Statistics and Documents (Section 73)
- Consultation on the matter of law reform (Section 74)
- Credit to GoN and Purchase of Government Debt Bonds

**(Chapter 9)** Regulation, inspection and supervision of the banks

- Bank's approval required for accepting deposits or giving credits (Section 76)
- Restriction on rate of interest (Section 77)
- License to be obtained from Bank (Section 78)
- Regulatory powers of Bank (Section 79)
- Banking and financial system and credit control (Section 80)
- Credit to prescribed sectors (Section 81)
- Information to be furnished to Bank (Section 82)
- Approval required to issue debentures and financial instruments (Section 83)
- Inspection and supervision (Section 84)
- Exchange of mutual cooperation (Section 85)
- Commercial banks and financial institutions to provide information to the Bank (Section 86A)
- Commercial banks and financial institution deemed to be problematic (Section 86B)
  - Acting against the interest of depositor, shareholder, and promoters,
  - Not fulfilling the financial liabilities,
  - Insolvency or going to be insolvent,
  - Non-compliance with or breach of this Act, prevailing laws, terms of license or regulation, directives or order of Bank,
  - Obtained the license on the basis of submitting false, fraudulent, wrong document or data,
  - Inability to maintain the capital fund as dictated by the law,
  - Initiation of the legal proceedings for liquidation or resolution or insolvency,
  - In case of undue delay in the process of voluntary liquidation where such proceeding has been initiated,
  - Carry out of the businesses or transaction in joint venture with foreign commercial bank or financial institutions which are insolvent or for which liquidator is appointed or the license is terminated under the provision of the law of respective country or transaction is banned fully or partially.
  - Unable to pay the due amount.
- Bank to take action against problematic commercial bank or financial institution (Section 86C)
  - Issue an order to issue new shares
  - Suspend the right of voting for the shareholder
  - Stop the dividend payment to any other amount to the shareholder
  - Determine the limitation to the bonus, salary, compensation and other expenses
  - Make necessary arrangement for corporate governance, internal control and risk management
  - Maintain sufficient capital and high proportion of liquidity or prohibit business transaction
  - Limit the transaction or prohibit sale of property or expansion/closure of branch
  - Prohibit from doing specific business
  - Issue an order to remove director/manager/staff
  - Receive prior approval of the bank for major capital expenditure, substantial commitments having major liabilities or for the expenditure of contingent liabilities
  - Suspend the Board of Director and takeover the management
  - Issue an order to remove from the post to single or more director or manager or employee
  - Issue an order to delist from the stock market
  - To prohibit payment of interest and principal for time bond auxiliary loan without having securities.
- Effect of the control of the Bank to any Commercial Bank or Financial Institution (Section 86D)
- The reformative measures and power to be used by the bank or the official appointed by the bank (Section 86E).
- Power of the bank for corrective action (Section 86F)
- Can be subject of resolution (Section 86G)
- Decreasing the capital of problematic commercial bank or financial institution (Section 86H)
- Right to appeal against the order of the bank (Section 86I)
- Establishment of Information Network (Section 87)
- Establishment of Credit Information Center (Section 88)

**(Chapter 9)** Provisions relating to resolution (Chapter added by amendment)

**(Chapter 10)** Balance sheet, auditing and report

**(Chapter 11)** Offenses, punishment and proceedings

**(Chapter 12)** Miscellaneous

### Major features of the amended NRB Act

- Preamble has been arranged with an emphasis on maintaining price and balance of payments stability, and overall financial sector stability supporting sustainable development.
- Audit Committee will be established comprising one Board member nominated by the Board as the Coordinator, one expert of this discipline nominated by the Board as a Member and Chief of the Internal Audit Department of NRB as Member Secretary.
- The NRB paid-up capital has been increased to five billion rupees from one billion rupees.
- NRB may inspect and supervise payment service provider and payment system operator licensed by it.
- Governor of NRB cannot be appointed in any designation of the BFIs after retirement.
- Deputy Governer and Executive Director cannot be appointed in any designation of BFIs for three years and other officers for two years after retirement. Even after this period, they should obtain prior approval from NRB for engaging in any such designation.
- Profit and loss statement shall be prepared by using Nepal Accounting Standards. Anything not expressly addressed by Nepal Accounting Standards shall be covered in accordance with the International Accounting Standards.
- Provision for fund management has been included which requires allocation of amounts to different funds.
- The provision of open market operation for maintaining liquidity has been reformulated in the Act. Besides repor and reverse repo, NRB could use other appropriate instruments and other measures for the purpose of OMO.
- Under section 79, NRB can issue to BFIs directives on Anti-Money Laundering (AML) and Combating Financing of Terrorism (CFT) covering areas like identification of clients as well as the classification of client risks and their management, fund transfer, furnishing of details on border of suspicious transactions including deposits to the FIU.
- The amendment has increased the power of NRB for remedial action in the resolution process of problem bank and financial institutions.
- A separate Chapter has been provided for the resolution process. Under this, following provisions are included,
  - Special Administration Group shall be formed for the settlement of the problem BFIs.
  - The group shall operate BFI except collecting deposit and providing loan.
  - There is also the provision of Bridge Institution or Unit for the operationalization of resolution of BFI.
  - During the resolution process, the rights of all the staff shall be suspended. Special Administration Group shall prepare new balance sheet and shall recommend for the improvement of financial status of BFIs.
  - All the actions and activities commenced prior to the resolution shall be suspended.
  - Special Administration Group could also request for, and obtain, mutual assistance from concerned institutions in foreign countries, if so required, to support resolution process, with the prior approval of the NRB.

## Banking Offence and Punishment Act, 2064

(Continue from page 557 of Advanced Banking Knowledge book)

## Company act, 2063

- Date of Authentication: 2063-7-7(3 November, 2006); Published Date: 2064-5-9(26 August, 2007)
- Chapters: 21
- Sections : 188

**Objectives**

- To create dynamism into the economic development of the nation by promoting investment in industries, trade, and business.
- To promote the use of economic liberalization.
- To make legal provision relating to incorporation, operation, management, and administration of the company much simpler, easier and more transparent.

**Features and provisions**

- Incorporation of the company
- Promotion of corporate good governance
- Defines the management tools of the company such as AOA, MOA, and BOD.
- Creates the features of a legal person.
- All companies must use suffix as Pvt. Ltd. or Ltd as per their nature.
- Few types of companies should be incorporated only as a public company
- Provision relating to the conversion of private company into public and _vice versa_.
- Establishment of Office of Company Registrar (OCR) which can provide service from branch office and outlets.
- Provision relating to share, capita , and debenture of companies.
- Board of Director (BOD) formation, Types of director and their rights and liabilities and also BOD meeting procedures.
- General meeting its types and agendas of the company.
- Account record keeping and auditing.
- Company winding up as per the voluntary, compulsory and with deregistration process
- Provision relating to the protection of shareholders.
- Provision relating to private, holding, subsidiary and foreign company.
- Provision relating to control the use of ultra vires by BoD. (Company should not go beyond the AOA and MOA)
- Provision relating to a proceeding of lawsuits and punishment.
- Provision of the substantial shareholder
- Compulsory provision of company secretary for a company which has more than 1 crore capital
- Compliance with the Money Laundering Prevention Act
- Provision of merger and acquisition of the company.
- Provision for conversion of a Development Committee into public company if the government gives permission.

### Types of general meeting

- First Annual General Meeting (FAGM)
- Annual General Meeting (AGM)
- Special/Extraordinary General Meeting (SGM)

1. First Annual General Meeting (FAGM)

- This meeting is held to approve all the documents which were submitted while registering the company.

2. Annual General Meeting (AGM)

- Chairperson or director shall call the Annual General Meeting.
- AGM should be conducted within 6 months after the end of the fiscal year.
- It can be extended up to three months with the approval of OCR.
- If a company can not conduct AGM within the predefined time, OCR schedule the time.
- If the company still do not call for AGM, the stakeholders can file a case in court for calling up AGM

_Process of Calling AGM_

- AGM notice should be published before 21 days of the AGM date mentioning the date/time, venue and agendas.
- AGM notice should be published at least two times in the national level newspaper.
- If any changes occur, notice should be published before 7 days of the AGM date.
- AGM will be hosted by the secretary, chaired by president and minute must be approved by all the members.
- This minutes copy should be submitted to OCR within 30 days from the date of approval

3. Special/Extraordinary General Meeting (SGM)

- Call by Board of Director, chairperson.
- Three parties can call SGM with a written request  Auditor,  Shareholders (at least 10% of share capital with minimum 3 shareholders), Shareholders (at least 25% of shareholders).
- After the written request from the above three parties, the director or president must call a Special General Meeting within 30 days.

Process of Calling SGM

- SGM notice should be published before 15 days of the SGM date mentioning the date/time, venue and agendas.
- AGM notice should be published at least two times in the national level newspaper.
- If any changes occur, notice should be published before 7 days of the SGM date.
- SGM will be hosted by the secretary, chaired by president and minute must be approved by all the members.
- This minutes copy should be submitted to OCR within 30 days from the date of approval.

Agendas of SGM

- Increase/decrease capital
- Share buyback
- Bonus share
- About Merger/acquisition
- Company name change etc

All the members of the BOD must attend the meeting physically. If not possible physically, use of video conference to use voting right.

## Electronic transaction act, 2063

## Money Laundering Prevention act, 2064

(For a brief description of what is money laundering and what constitutes the offense for natural person or for business entity, refer to the topic "Money Laundering" on Comprehensive Guide (Contemporary and GA)).

1. Reporting unit and reporting procedure -- Reporting units are those institutions which are assigned to report their financial transactions. It includes -- all the financial and non-financial firms, professional and businesses (e.g. B and FI, Casinos, Real estate).
2. It defines money laundering terrorist financing offeses.
3. Restriction to open account of a fictious person (imaginary person)
4. Restriction to make anonymous transactions
5. Restriction to operate shell banking (Shell banking -- carrying out banking operation by registering in registrar office but without physical existance)
6. Provision of customer due diligence (CDD) -- All the B and FIs and other firms who carry otu the financial transaction must use Know Your Customer (KYC) to maintain customer due deligence (CDD).
7. Monitoring and record keeping of cross broder corresponding banking. (Correspondence banking -- Performance of transaction by a bank of foreign country on behalf of home country based on correspondence)
8. Institutional provision for the prevention of money laundering and terrorist financing (DLMI, FIU).
9. Provision of seizure and confiscation of suspicious property and visa/travel documents of a suspicious person while investigating.
10. Provision of punishment of ML and TF offenses as per natural person and legal person.
11. Free/open time limitation for ML and TF case to case the file
12. Provision of rewarding information providers upto 10 lakhs or 10% of the crime amount whichever is less.
13. Provision relating punishment to false FIR providers as up to NRs 10000 in fines.
14. Provision to prepare "National Risk Assessment Report" periodically.
15. Provision of reporting of suspicious transaction to FIU promptly by reporting unit.

### Achivements after formation of MLP act, 2064

1. Establishment of reporting unit
2. Increased use of KYC for CDD
3. Need to disclose the source of income properly
4. Restriction to operate shell banking
5. Establishment and operation of FIU (Financial Information Unit)
6. Establishment of DMLI (Department of Money Laundering Investigation)
7. Support to control capital flight
8. Compliance with other laws
9. Suport promotion of financial good governance
10. Control of ML and TF

### Weaknesses of MLP act, 2064

1. Lack of specialization in investigation
2. The dilemma in functional jurisdiction
3. Complex provision
4. Open border
5. Maximum use of Indian currency
6. Problem in compliance with other legal provisions
7. Political and crime nexus
