# Nepal Rastra Bank Act, 2058 (2002)

## Major features of the amended NRB Act

- Preamble has been arranged with an emphasis on maintaining price and balance of payments stability, and overall financial sector stability supporting sustainable development.
- Audit Committee will be established comprising one Board member nominated by the Board as the Coordinator, one expert of this discipline nominated by the Board as a Member and Chief of the Internal Audit Department of NRB as Member Secretary.
- The NRB paid-up capital has been increased to five billion rupees from one billion rupees.
- NRB may inspect and supervise payment service provider and payment system operator licensed by it.
- Governor of NRB cannot be appointed in any designation of the BFIs after retirement.
- Deputy Governer and Executive Director cannot be appointed in any designation of BFIs for three years and other officers for two years after retirement. Even after this period, they should obtain prior approval from NRB for engaging in any such designation.
- Profit and loss statement shall be prepared by using Nepal Accounting Standards. Anything not expressly addressed by Nepal Accounting Standards shall be covered in accordance with the International Accounting Standards.
- Provision for fund management has been included which requires allocation of amounts to different funds.
- The provision of open market operation for maintaining liquidity has been reformulated in the Act. Besides repor and reverse repo, NRB could use other appropriate instruments and other measures for the purpose of OMO.
- Under section 79, NRB can issue to BFIs directives on Anti-Money Laundering (AML) and Combating Financing of Terrorism (CFT) covering areas like identification of clients as well as the classification of client risks and their management, fund transfer, furnishing of details on border of suspicious transactions including deposits to the FIU.
- The amendment has increased the power of NRB for remedial action in the resolution process of problem bank and financial institutions.

- A separate Chapter has been provided for the resolution process.
- Under this provision, Special Administration Group shall be formed for the settlement of the problem BFIs.
- The group shall operate BFI except collecting deposit and providing loan.
- There is also the provision of Bridge Institution or Unit for the operationalization of resolution of BFI.
- During the resolution process, the rights of all the staff shall be suspended. Special Administration Group shall prepare new balance sheet and shall recommend for the improvement of financial status of BFIs.
- All the actions and activities commenced prior to the resolution shall be suspended.
- Special Administration Group could also request for, and obtain, mutual assistance from concerned institutions in foreign countries, if so required, to support resolution process, with the prior approval of the NRB.

