# Management, information and communication technology

## Organization: concept, structure, objectives



(Page 386, 389, 391, 619, Advanced Banking Knowledge)

### Organization change and development

(Page 426, Advanced Banking Knowledge)

## Management: introduction, concept, objective, scope and function

(Continue from Page 353, Advanced Banking Knowledge)

(for a more detailed discussion on meaning and definition of management refer to Comprehensive Guide (Contemporary and GA))

### Management Information System 

MIS is the study of people, technology, organizations and the relationships among them. MIS professionals helps firms realize maximum benefit from investment in personal, equipment, and business processes. MIS is a people-oriented field with an emphasis on service delivery through the use of technology for decision-making, coordination, control, analysis, and visualization of information in an organization.

Business use information systems at all levels of operation to collect, process and store data. Management aggregates and disseminates this data in the form of information needed to carry out the daily operations of business. Everyone who works in business, from someone who pays the bills to the person who makes employment decision, uses information system.

In public governance, MIS are the tools to promote transparency, accountability and participation. More specifically, recent approaches to delivering bureaucratic services are expected to meet their goals of public orientation and result based performance evaluation aided through information system. Establishment of computerized Integrated Financial Management Information System (IFMIS) is being mulled over to implement single platform central accounting system as a part of a public finance management reform initiative by Government of Nepal with support of World Bank. For example, under this system information about expenditure made by the Department of Roads and the revenue collected by the Inland Revenue Department will be disseminated via the same platform. Also the concept of digital National Identity Card based is a part of broader vision of government, currently under delegation of the National ID Management Center (NIDMC) under aegis of Ministry of Home Affairs, to aggregate vital information database of the citizens.

In a corporate setting, the ultimate goal of the use of a management information system is to increase the value and profits of the business. This is done by providing managers with timely and appropriate information allowing them to make effective decisions within a shorter period of time.

Informational system offer organization management with following useful features:

1. Accuracy
  - Requires effective control of operations
  - Helps divert management efforts and energies on high priority problems
2. Timeliness
  - Address problems that require immediate attention
  - Saves management from future troubles and provides reference for timely decision 
3. Flexibility
  - Business and economy is highly dynamic in nature, rigid control of which would not be suitable for changing environment
  - Strategic planning must allow for adjustments for unanticipated threats and opportunities and managers must make modifications in controlling methods, techniques and systems.
4. Acceptability
  - Control system should function in a way understandable and acceptable to employees
  - Operation procedures should avoid mistakes and resentment from customers
5. Integration
  - Management operations should work in a way consistent with corporate values and culture.
6. Economic feasibility
  - Cost of management operations must be balanced against its benefits.
7. Strategic placement
8. Correction action

While management information systems can be used by any and every level of management, the decision of which systems to implement generally falls upon the chief information officers (CIO) and chief technology officers (CTO). These officers are generally responsible for the overall technology strategy of an organization including evaluating how new technology can help their organization. Once decisions have been made, IT directors, including MIS directors, are in charge of the technical implementation of the system. Upon implementation, the assigned users will have the appropriate access to relevant information. It is important to note that not everyone inputting data into MIS need necessarily be management level.

In banking and finance, the MIS represents the electronic automation of several different kinds of counting, tallying, record-keeping, and accounting techniques, of which the by-far oldest was the ledger on which the business owner kept track of his or her business. More recently, the role of MIS in public and private governance and banking is further invigorated by widespread networking facilities made possible through internet.

#### Advantages of Management Information System

- Improve an organization’s operational efficiency, add value to existing products, engender innovation and new product development, and help managers make better decisions.
- Companies are able to identify their strengths and weaknesses due to the presence of revenue reports, employee performance records etc. Identifying these aspects can help a company improve its business processes and operations.
- Giving an overall picture of the company.
- Acting as a communication and planning tool.
- The availability of customer data and feedback can help the company to align its business processes according to the needs of its customers. The effective management of customer data can help the company to perform direct marketing and promotion activities.
- MIS can help a company gain a competitive advantage.
- MIS reports can help with decision-making as well as reduce downtime for actionable
items.

#### Disadvantages of Management Information System

- Retrieval and dissemination are dependent on technology hardware and software.
- Potential for inaccurate information.

_note_: ideas excerpted from Comprehensive Guide (Contemporary and GA) in addition external literature.

### Time management

### Crisis management

(Page 399, Advanced Banking Knowledge)

### Conflict management

(Page 407 and Page 427, Advanced Banking Knowledge)

### Change management

(Page 424, Advanced Banking Knowledge)

### Knowledge management

Knowledge management is an emergent management issue. Knowledge is defined as the remembering of previously learned materials. In other words, knowledge is information that is relevant, actionable, and at least partially based on experience. Similarly, knowledge can mean information, awareness, knowing, cognition, sapience, experience, skills, insight, competence, know-how, practical ability, capability, learning, wisdom and so on. The definition depends on the context in which the term is used.

Knowledge management is concerned with the process of identifying, acquiring, distributing and maintaining knowledge that is essential to the organization. Knowledge management can be explained differently under varying circumstances of intended information.

```{r knowledge-explain-circumstance}
tribble(
  ~"Scope", ~"Explaination",
  "Result", "To have the right knowledge at the right place, at the right time and in the right format",
  "Process", "The systematic management of process by which knowledge is defined, created, gathered, shared and applied",
  "Technology", "Business intelligence, collaboration, search engine, intelligence agents"
) %>% 
  knitr::kable(booktabs = TRUE, longtable = TRUE, caption = "Various contexts of knowledge use and its relevance to management") %>% 
  kableExtra::kable_styling(font_size = 8) %>% 
  kableExtra::column_spec(column = 1:2, width = c("4em", "25em"))
```

The combination of all the scope dependent definition provide a clearer picture of what knowledge management entails. In practice, knowledge management involves the identification and mapping of intellectual assets within an organization focusing on the organization's unique resources and their crucial functions.

Basic reasons for understanding knowledge management can be highlighted with following points:

- Marketplace are increasingly competitive and the rate of innovation is rising
- Reduction in staffing creates a need to replace informal knowledge with formal methods
- Competitive pressure reduces the size of the workforce that holds valuable business knowledge
- The amount of time available to experience and acquire knowledge is diminished
- There is need to manage increasing complexities as small operating companies are transnational sourcing operations
- Changes in strategic direction may result in the loss of knowledge in a specific area.

### Resource management

### Stress management

## Human Resource management

Human resource is the most important capital that has the competitive advantages over the other resources for any economic entity. Managing people for any organisations/institutions has become the paramount factor in order to have competitive edge. Single person can't achieve organizational goals; it requires committed, loyal team and expertise of different areas. In order to create team that aligns in achieving the vision of organization, Human Resource Management plays a vital role. The highly expected potential makes the human resources very decisive consideration to the success of an organization and it can bring the greatest return on investment for sustainable competitive advantage. The banking industry is a backbone for growth of any economy and an important component of the financial sector for allocation and utilization of financial resources. Banking sector plays a fundamental role in the economic development and considered as a barometer of the financial system of the country.

Human Resource Management (HRM) as such is a function in an organization designed to maximize the performance of the employees to achieve specific strategic objectives, by means of managing people and abiding by the policies and system. So, every organization requires skilled, committed and loyal manpower to develop. Development of an organization eventually supports for the development of the country by contributing to the economy.

### Development of human resource management in Nepal

Nepal may not be in the pace with other developing countries in terms of its human resource management but has definitely come a long way. In 1980s with the entry of some foreign joint venture banks and companies the concept of HR Management seems to arise as these companies had structured HR processes, from recruitment to employees' grievance handling. Further with the arrival of more Joint Ventures and INGO in Nepal the HR Management terms gained momentum. These organizations were successful in inspiring other Nepalese business organization with their effective employee management. In Nepalese Institutions HR department as such did not exist in the form of a separate body till 2000 A.D. Human resource department function was combined with the administrative department and this department carried out the role of human resource departments. Moreover, HR function was limited to carrying out routine activities such as, record keeping, updating the payroll and maintaining relations with employees. Majority of organizations didn't involve their human resource heads in the formulation of strategy, decision making and business planning process. Vital decisions related to employees were taken by executives without consulting the human resource managers. But then, regulation of Nepal Rastra Bank (NRB) for all commercial banks to have a mandatory separate HR department was the start of prudent HR practices in BFIs. Then after, efficient HR management in BFIs was among the core objectives of reform programs including Financial Sector Strategy Statement (2000) and Financial Sector Reform Program (2004). Later, in the mid and late 2000s, Organizations irrespective of their sizes, have a human resource department and apart from that there are many independent human resource consultancies that offer great services to organizations. Initially, various HR companies stepped into as recruitment service providers and later entering into areas such as employee training and development, HR system formulation, and even HR process outsourcing in recent years.

### HRM practices

Human resource management practices are the management of people within the internal environment of organizations, comprising of the activities, policies, and practices involved in planning, organizing, developing, utilizing, evaluating, maintaining and holding the appropriate numbers and skill mix of employees to achieve the organization’s objectives. HR management, which used to be considered as a non-innovative and paper-intensive job of organizational management, now with rapid change in technology is considered as fundamental element for the success of an organization. With the rapid change and innovation of new technologies, institutions are able to mitigate various challenges in human capital management in terms of employee engagement, competitive pay, talent attraction and retention and succession planning. Institutions in developed countries are focusing on the next frontiers in HR management such as using artificial intelligence (AI) in workplaces to effectively measure the performance of employees. Nowadays, Nepalese organizations to attain their organizational objectives, are also trying to catch-up with the other developed and developing countries in term of managing human resources. Some institutions have been efficiently practicing HR management principles and techniques for better productivity. They have started to use modern technologies for better evaluation of their staff and cost-benefit analyses. At present, digitization and use of HR software are useful tools to reduce the paperwork and manual hassles in record keeping, monitoring and evaluation. Nevertheless, As HR management is a very systematic process, proper policies are necessary to govern the activities. 

### HRM in Banks

Banking is a service industry and has been and will always be a People Business. Management of people and management of risk are two key challenges for banks. The success of an organization is determined by how efficiently it is able to manage the people and the risks associated with the banking business. Effective risk management may not be possible without efficient and skilled manpower. Besides, risk management, customer care and satisfaction is another essential element for sustaining banking business. People dealing in front line will give the first impression about the organization. Monetary value may sometime become crucial but there are other valid reasons why internal as well as external customers select and stay with a particular bank.

Rapid growth of banks and financial institutions has created employment opportunities as well as growth in the sector. The number of branches in private and public banks has significantly increased resulting the requirement of skilled manpower in this sector. At present, skilled and experience HR resources are becoming scarce; both in quality and quantity. Any resource that is in short supply needs appropriate management for proper functioning thus, banks require to pay much attention to the entire Human Resource Management process. To analyze future requirements of the organization and steadily calibrate recruitment process Human resource management is important.

The network of banking business is very immense and spread all over the country. Due to this wide spread network, it brings together people from different origins and of different workforce profile working together under the same roof. This necessitates banks to follow different HR practices in order to deal with them effectively so that their full potential is utilized. Advancement in technology has shifted customer preferences compelling banks to adopt online and core banking services. There is an emergent need for techno friendly HR for effective and efficient business operation. Therefore organization requires to balance workforce integrating new energetic youth with experienced professional. Thus HR Management practices helps in creating balance by undergoing some cultural and management adjustments.

Working methodology and environment is changing in banking business due to the change in policies, procedures and technology. Continuous training and development of human resources is essential for adopting and implementing change. Hence, HR management practices will deliver focus on empowering employees, measure overall performances, augment human element for excelling the performance and is also responsible for planned retirement of employees.

### Challenges

Due to rapid changes in the business world, globalization, technological advancement, change in customer taste and habits and new techniques of business operations, human resource in various organizations are facing diverse kinds of problems, and to manage these situations in splendid way organisations are facing variety of issues and challenges. In comparison to other sectors, banking Sector is most developed, Organized and diversified. This sector is an important tool for facilitating the development of economy. Some of the pragmatic challenges in managing human resource are explained below.

- In most of the organizations due to the limited understanding and knowledge concerning the significance of human resources management, human resource departments are headed by educated person but doesn't possess the basics of human resource or junior staff with no relevant experience. Generally, lack of proper knowledge in terms of human resource management were and till date has been a challenge for the independent functioning in goal achieving process.
- Large number of people entering banking sector required to be transformed into useful human resources. Therefore identifying, arranging and conducting training and development programs for heterogeneous human resource to match with changing industry requirement is another challenges. Some of the banks went for merger and acquisitions to increase their capital base. Thus managing HR and creating a balanced organization that are created from mergers and acquisitions is also a challenge.
- Banking industry is undergoing sever changes due to the composition of their staff, training requirements, combinations of corporate culture, ethics and values in them. Developing and instilling all the elements to diverse Human Resource is Challenge for banking sector.
- Attracting and retaining employees, hiring people with long term commitment and believe towards organization, motivating and satisfying employees for reducing attrition rate are other big challenges

### Conclusion

Technology has become one of the biggest drivers of change in Nepalese banking industry as it has been transforming limited hours banking services into 24 hours a day banking, seven days in a week and in simplifying the service levels as well. Improved technologies are being adopted by banks for upgrading their products, services, work methods, work norms, and enhancing skills and motivating employees .Banks are in race to position themselves as a single-stop shop financial service provider with a fairly extensive range of products, including deposit products, loans, credit cards, debit cards, depository services, investment advice, bill payments, ATMs, mobile banking, internet banking and various other transactional services. Banks are also entering into the business of selling third-party products such as mutual funds and insurance to the retail customers. Banks have been investing huge amounts to computerize and modernize their branches and installing new delivery channels. In line with these changes, technologies play prominent role in both the lives of employees and human resource management (HRM), which seems to be affected in multiple ways. Now, banks necessities to recognize that the investment and technology are important pillars, but human capital, is the most valuable resource for the achievements of the goals set by the organization. Therefore greater emphasis for managing human resources is prerequisite for organizational success. In the current scenario, Human Resource Management, Human Resource Development, Organizational Development and Organizational Behavior together distinctly plays a very important role for smooth operation of an organization. Therefore, the preliminary objectives of the bank should be integration of HRM strategies with the business strategies. It must be able to create team work, commitment and loyalty among the employees to improve the efficiency and optimal utilization of its human capital. Sound and effective HRM policies and practices for the sake of organizations as well as personal development should be sensed strongly at every level and equal effort should be made to improvise the culture of the organization.

## Risk management

In the course of their operations, banks are invariably faced with different types of risks that may have an adverse impact upon their business. Risk management in bank operations involves,

- Risk identification
- Risk measurement/appraisal and,
- Risk assessment

Broadly, the objective of risk management is to minimize negative effects the risks can have on the financial result and capital of a bank. Banks are therefore required to form a special organizational unit in charge of risk management, as well as prescribe procedures for identification, assessment and aversion/mitigation of risk. Following section describes the types of risks banking institutions are faced with.

### Types of risk

**1. Systematic risk or market risk**

Systematic risk is the risk of asset value change associated with systematic factors, also sometimes imprecisely referred to as market risk. By its nature, this risk can be hedged, bu cannot be diversified completely away. All investors assume this type of risk, whenever assets owned or claims issued can change in value as a result of broad economic factors. As such, two of the important systematic risks in banking sectors are

- variation in the general level of interest, and
- the relative value of currencies.

Because of the banks dependence on these systematic factors, most try to estimate the impact of these on performance, attempt to hedge against them and thus limit the sensitivity to variations in un-diversifiable factors. Accordingly, most will track interest rate risks closely and try to manage firm's vulnerability to interest rate variation. At the same time, international banks with large currency positions closely monitor their foreign exchange risk and try to manage, as well as limit, their exposure to it. In a similar fashion, some institutions with significant investments in one commodity such as oil, through their lending activity or geographical franchise, concern themselves with commodity price risk.

As with other forms of risk, the potential loss amount due to market risk may be measured in a number of ways. In short term risk management practice, a well established convention is to use Value at Risk (VaR).

VaR contains a number of limiting assumptions that constrain its accuracy in risk assessment. A guiding assumption to calculation being the composition of the portfolio measured remains unchanged over the specified period. Although reasonable for short time horizons, it should be noted that many of the positions in the portfolio change over longer time horizons. The VaR of the unchanged portfolio is no longer relevant. Likewise, the variance, covariance as well as historical simulation approach to calculating VaR also assumes that historical correlations are stable and will not change/breakdown in the future. In addition, care has to be taken regarding the intervening cash flow, embedded options, changes in floating interest rates to the financial positions in the portfolio. They cannot be ignored if their impact can be large.

**2. Credit risk**

Credit risk concerns with the adverse impacts on the financial position and capital of the bank caused by borrower's default on its obligation to the bank. It arises from non-performance (inability or unwillingness) by a borrower. This can affect the lender holding the loan contract, as well as other lenders to the creditor. Therefore, the financial condition of the borrower as well as the current value of any underlying collateral is of considerable interest to its bank. The real risk from credit is the deviation of portfolio performance from its expected value.

Credit risk is diversifiable, but difficult to elliminate completely. This is because a portion of the default risk may, in fact, result from the systematic risk. In addition, the idiosyncratic nature of some portion of these losses remains a problem for creditors in spite of the beneficial effect of diversification on total uncertainty. This is particularly true for banks that lend in local markets and one that take on highly illiquid assets. In such cases, the credit risk is not easily transferred, and accurate estimates of loss are difficult to obtain.

The credit risk is primarily that of the lender and includes lost principal and interest, disruption of cash flows, and increased collection costs. The loss may be complete or partial and can arise in a number of circumstances. For example,

- A company is unable to repay asset-secured fixed or floating charge debt.
- A business or government bond issuer does not make a payment on a coupon or principal payment when due
- A business or consumer does not pay a trade invoice when due
- A business does not pay an employee's earned wages when due
- A government grants bankruptcy protection to an insolvent consumer or business
- An insolvent bank won't return funds to a depositor
- A consumer may fail to make payment due on a mortgage loan, credit card, line of credit, or other loan
- An insolvent insurance company does not pay a policy obligation.

To reduce the lender's credit risk, the lender may perform a credit check on the prospective borrower, may require the borrower to take out appropriate insurance, such as mortgage insurace or seek security or guarantees of third parties. In general, the higher the risk, the higher will be the interest rate that the debtor will be asked to pay on the debt.

Significant resources and sophisticated programs are used to analyze and manage the credit risk. Some companies run a credit risk department whose job is to assess the financial health of their customers, and extend credit (or not) accordingly. They may use in house programs to advice on avoiding, reducing and transferring risk. They also use third party provided intelligence. Most lenders employ their own models (credit scorecards) to rank potential and existing customers according to risk, and then apply appropriate strategies.

With products such as unsecured personal loans or mortgages, lender charge a higher price for higher risk customers and vice versa. With revolving products such as credit cards and overdrafts, risk is controlled through the setting of credit card limits. Some products also require collateral, usually an asset that is pledged to secure the repayment of the loan.

Credit scoring models also form part of the framework used by banks or lending institutions to grant credit to clients. For corporate and commercial borrowers, these models generally have qualitative and quantitative sections outlining various aspects of the risk including, but not limited to, operating experience, management expertise, asset quality, and leverage and liquidity ratios, respectively. Once this information has been fully reviewed by credit officers and credit committees, the lender provides the funds subject to the terms and conditions presented within the contract.

**3. Counterpary risk**

Counterparty risk is the risk that a trading partner will not pay as obligated on a bond, credit derivative, trade credit insurance or payment protection insurance contract or other trade or transaction. The non-performance may arise from counterparty's refusal to perform due to an adverse price movement caused by systematic factors, or from some other political or legal constraints that was not anticipated by the principals. Diversification is the major tool for controlling non-systematic counterparty risk. Counterparty risk is like credit risk, but it is generally viewed as a more transient financial risk associated with trading than standard creditor default risk. In addition, counterparty's failure to settle a trade can arise from other factors beyond a credit problem.

Financial institutions may hedge or take out credit insurance as a safeguarding measure. Offsetting counterparty risk is not always possible, e.g. because of temporary liquidity issues or longer term systemic reasons. Counterparty risk increases due to positively correlated risk factors. Accounting for correlation between portfolio risk factors and counterparty default in risk management methodology is not trivial.

**4. Liquidity risk**

Liquidity risk is the possibility of financial or capital loss of a bank caused by it's inability to meet all its due obligations, also known as funding crisis. While some would include the need to plan for growth and unexpected expansion of credit, the risk here is seen more correctly as the potential for a funding crisis. Such a situation would inevitably be associated with an unexpected event, such as a large charge off, loss of confidence, or a crisis of national proportion such as currency crisis. In any case, management here centers on liquidity facilities and portfolio structure. Recognizing liquidity risk leads the bank to recognize liquidity itself as an asset, and portfolio design in the face of illliquidity concerns as a challenge.

**5. Operational risk**

Operational risk is associated with the problems of accurately processing, settling, and taking or making delivery on trades in exchange for cash. It also arises in record keeping, processing system failures and compliance with various regulations. As such, individual operating problems are small probability events for well-run organizations but they expose a firm to outcomes that may be quite costly. Nonetheless, omissions in the work or employees and inadequate internal procedures and processes also constitute operational risk.

_Basel II regulations definition (adopted by European Union Solvency II Directive)_

"The risk of a change in value caused by the fact that actual losses, incurred for inadequate or failed internal processes, people and systems, or from external events (including legal risk), differ from the expected losses."

In October 2014, the Basel Committee on Banking Supervision proposed a revision to its operational risk capital framework that sets out a new standardized approach to replace the basic indicator approach and the standardized approach for calculating operational risk capital.

It can also include other classes of risk, such as fraud, security, privacy protection, legal risks, physical (e.g. infrastructure shutdown) or environmental risks. Operational risk is a broad discipline, close to good management and quality management. In similar fashion, operational risks affect client satisfaction, reputation and shareholder value, all while increasing business volatility. Contrary to other risks (e.g. credit risk, market risk, insurance risk) operational risks are usually not willingly incurred nor are they revenue driven. Moreover, they are not diversifiable and cannot be laid off, meaning that, as long as people, systems and processes remain imperfect, operational risk cannot be fully eliminated.

Operational risk is, nonetheless, manageable as to keep losses within some level of risk tolerance (i.e. the amount of risk one is prepared to accept in pursuit of his objectives), determined by balancing the costs of improvement against the expected benefits. Wider trends such as globalization, the expansion of the internet and the rise of social media, as well as the increasing demands for greater corporate accountability worldwide, reinforce the need for proper operational risk management (ORM). This dynamic topic is defined as a continual cyclic process which includes assessment, decision making and implementation of risk controls, which results in acceptance, mitigation, or avoidance of risk.

_Methods of operational risk management_

Basel II and various Supervisory bodies of the countries have prescribed various soundness standards for Operational Risk Management for Banks and similar Financial Institutions. To complement these standards, Basel II has given guidance to 3 broad methods of Capital calculation for Operational Risks;

1. Basic indicator approach. Based on annual revenue of the financial institution.
2. Standard approach. Based on annual revenue of each of the broad business lines of the financial institution.
3. Advanced measurement approaches. Based on internally developed risk measurement framework of the bank adhering to the standards prescribed (includes methods such as IMA, LDA, Scenario-based, Scorecard)

The ORM framework should address risks with respect to following aspect:

- Identification
- Measurement
- Monitoring
- Reporting
- Control, and
- Mitigation

**6. Legal risk**

Legal risk is the risk of loss caused by penalties or sanctions originating from court disputes due to breach of contractual and legal obligations, and penalties and sanctions pronounced by a regulatory body. In other words, legal risks are endemic in financial contracting and are separate from the legal ramifications of credit, counterparty, and operational risks. New statutes, tax legislation, court opinions and regulations can put formerly well-established transactions into contention even when all parties have previously performed adequately and are fully able to perform in the future. A type of legal risk arises from the activities of an institution's management or employees. Fraud, violations of regulations or laws, and other actions can lead to catastrophic loss, as recent examples in the thrift industry have demonstrated.

All financial institutions face all these risks to some extent. Non-principal, or agency activity involves operational risk primarily. Since institutions in this case do not own the underlying assets in which they trade, systematic, credit and counterparty risk accrues directly to the asset holder. If the latter experiences a financial loss, however, legal recourse against an agent is often attempted. Therefore, institutions engaged in only agency transactions bear some legal risk, if only indirectly.

**7. Foreign exchange risk**

Foreign exchange risk is the risk that exists when a financial transaction is denominated in a currency other than that of the base currency of the company. Foreign exchange (FX) risk also exists when the foreign subsidiary of a firm maintains financial statements in a currency other than the reporting currency of the consolidated entity. The risk is that there may be an adverse movement in the exchange rate of the denomination currency in relation to the base currency before the date when the transaction is completed.

Investors and businesses exporting or importing goods and services or making foreign investments have an exchange risk mostly in settings with inefficient foreign exchange market. A deviation from one or more of the three international parity conditions (purchasing power parity, interest rate parity and the international Fisher effect) suggest some exposure to foreign exchange risk.

Firms with exposure to foreign exchange risk may use a number of foreign exchange hedging strategies to reduce the exchange rate risk. Transaction exposure can be reduced either with the use of the money markets, foreign exchange derivatives such as forward contracts, futures contracts, options, and swaps, or with operational techniques such as currency invoicing, leading and lagging of receipts and payments, and exposure netting.

## Information technology

## Business organization and environment

- A business is any organization set up to provide goods and/or services.
- Business aim to satisfy the needs and desires of their customers by selling a good or providing service.
- To produce goods and services, a business needs to combine human, physical, financial, and entrepreneurial resources. These resources are referred to as the factors of production, combining land, labor, capital and enterprise:

1. Land: Natural resources used in the production process, e.g. wood, water, physical land, fish, water, metal ores and minerals.
2. Labor: Physical human effort and psychological intellect used in the production process.
3. Capital: Non-natural (manufactured) resources used to further the production process, e.g. tools, equipment, machinery, vehicles and buildings.
4. Enterprise: An individual with the necessary skills and ability to take risks in organizing the other factors of production to generate output in a profitable way.

- The production process adds value to the final goods and services sold to customers. Value added is the process of creating a product that is worth more than the cost of the inputs used to produce it, e.g. bottled orange juice is worth more than the original oranges grown on a farm.
- Businesses strive to add value to a good or service so that the product better meets the needs arid wants of their customers.
- Value added is measured as the difference between the cost of the inputs in the production process and the price of the final output.

**Functions of business and their roles**

### Human resources

- Human resource management oversees staffing (personnel) within an organization.
- Human resource management (HR) issues such as recruitment, dismissal, training and development, redundancies, appraisals, performance management, career planning and the general welfare (well-being) of the firm's employees.
- The HR department must comply with employment legislation (labor laws), e.g. minimum wage legislation, regulations about working hours, equal opportunities law, and anti-discrimination acts.

### Finance and accounts

... continue from IB Diploma Business Management Study and Revision Guide.pdf (psc_preparation...)
