# Economics, fiscal and monetary policy

## Monetary policy for the FY 2020/21

In accordance with the provision made in the Nepal Rastra Bank Act, 2002, Nepal Rastra Bank (NRB) has been formulating and implementing monetary policy with the objective of maintaining economic stability and sustainable development of the economy through price and balance of payments stability. To attain these objectives, the bank is focusing on the functions that include effective liquidity management, promotion of competitive financial resources for productive use, effective foreign exchange reserve management and expansion of access to finance.

The governor of NRB, Maha Prasad Adhikari presented the monetary policy for the fiscal year 2020/21 on 17 July that targeted an annual economic growth rate of 7% and consumer price inflation rate no higher than 7%. The monetary policy aims to address the economic effects of COVID-19 and provide relief to various sectors affected by the pandemic.

Following general expectations are made while setting framework of action for the current fiscal year.

- The world economy is expected to revive in 2021. The IMF has projected the world economy to expand by 5.4% in 2021. Consumer inflation is projected to remain at 1.1% in advanced economies and 4.5% in the emerging and developing economies.
- Government of Nepal has targeted 7 percent economic growth in 2020/21. Agricultural output is expected to expand given favorable monsoon for paddy plantation and the expected expansion of credit to agriculture sector along with the influx of labor force. Industrial and service sectors are also expected to expand provided that COVID-19 comes under control at the earliest.
- Banking system has adequate liquidity along with declining lending rates. Given this, economic activities are expected to gain momentum with the help of effective implementation of targeted credit programs.
- The expected expansion of economic activities is likely to create inflationary pressure. However, increase in domestic output as well as improvement in supply management will help maintain price stability.
- Import is expected to rise along with the expansion of economic activities. Even though export and remittances are expected to remain at the same level of the last year, foreign debt mobilization by the GoN will support maintaining external sector stability.

### Highlights^[https://nepaleconomicforum.org/neftake/key-highlights-of-monetary-policy-fy-2020-21/]

1. The new monetary policy has increased the credit to core capital plus deposit (CCD ratio) to 85 percent from previously maintained 80 percent. This will allow banks to issue more loans and advances against deposits as 5 percent lesser is required to be set aside as a reserve to maintain liquidity.

2. Extension of loan repayment and grace period

The policy has extended the period of loan repayment for business enterprises that have been affected by the pandemic. The central bank has set a loan moratorium on principal and interest payments for businesses severely affected during the crisis until one year, partially affected borrowers until 9 months, and limited impacted businesses until 6 months. It has also permitted banks and financial institutions (BFIs) to extend further loans to industries affected by the pandemic by 20 percent of working capital maintained at mid-April. The policy has also increased the grace period on loan repayments as the lockdown had affected the construction work of several projects. Sectors most affected by the pandemic by the pandemic will get a grace period extension of one year. For the hotels accommodative of tourists, arrangements will be made to extend the grace period by two years.

3. Revision of refinancing facility and minimum investment in terms of loans to priority sectors

The new policy has revised the minimum investment in terms of loans to priority sectors and increased the range of refinancing facilities to increase access to such subsidized loans. As per the policy, export oriented-businesses and sick industries will get refinancing facilities at a maximum interest rate of 3 percent, while SMEs will avail credit at a maximum interest rate of 5 percent. The policy requires commercial banks to invest at least 15 percent of their loan portfolio in the agricultural sector, 15 percent to small, medium-sized enterprises, and 10 percent to the hydropower sector.

4. Provision for a cap on the distribution of cash dividends for BFIs

For the BFIs, the policy has introduced a cap on the distribution of cash dividends. For BFIs with a distributable profit lower than 5 percent of their paid-up capital, distribution of cash dividend is prohibited. Similarly, for BFIs with a distributable profit higher than 5 percent of their paid-up capital, distribution of 30 percent of dividends as cash dividends is permitted. However, such companies cannot distribute cash dividends exceeding their deposit weighted average maintained in Asadh 2077.

5. Restricted BFIs on charging various service fees

The central bank has barred banks and financial institutions from charging excessive service fees. While commercial banks can now take only 0.75 percent service charge while issuing loans, development banks and finance companies can take only 1 percent and 1.25 percent service charge from borrowers, respectively. In addition, the central bank has prohibited banks from charging the public for interbank ATM withdrawal until the COVID-19 crisis is over.

6. Encourages mergers between BFIs

The monetary policy promotes mergers between BFIs. It has announced that it would allow merged entities to collect 10 percent more corporate deposits than the fixed cap. Moreover, for the promoters and chief personnel of the merged entities, the cooling period will not be applicable. To address the already saturated microfinance sector, the monetary policy has halted the issuance of licenses for new microfinance companies. Any microfinance license already under the process of issuance has also been abandoned.

Others highlights of the monetary policy include the following:

- The repo rate has been reduced to 3 percent from 3.5 percent.
- The cash reserve ratio to be maintained by the BFIs is kept intact at 3 percent. Similarly, the statutory liquidity ratio to be maintained by commercial banks, development banks, and finance companies has been kept intact at 10 percent, 8 percent, and 7 percent respectively.
- A liquidity facility rate of 5 percent will be maintained as the upper limit of the interest rate corridor.
- The deposit collection rate, which has been established as the lower limit of the corridor will be reduced to 1 percent from previously maintained 2 percent.

### Monetary policy framework

- The focus of the policy is on maintaining macroeconomic stability along with supporting the growth target set by the GoN.
- Financial resources will be mobilized towards expanding economic activities, generating employment and enhancing sustainable economic development.
- Liquidity will be managed considering the likely pressure on price and external sector stability.
- BFIs consolidation will be on priority in order to foster financial sector development and stability.
- Access to finance and quality of financial services will be enhanced through development of financial infrastructures.
- Digitization will be promoted to make payment system more secure, healthy and efficient.
- Monetary management will focus on containing consumer price inflation within 7 percent in 2020/21.
- Monetary management will be carried out to ensure external sector stability. In this regard, foreign exchange reserves sufficient to cover the prospective merchandise imports of goods and services for at least 7 months will be maintained.
- Monetary management will be directed towards supporting to attain the targeted economic growth keeping economic recovery in priority.
- Given the basis of nominal GDP for monetary projection, growth of broad money (M2) and private sector credit have been projected at 18 percent and 20 percent respectively

### Financial sector provision

Policy will focus to expand credit on agriculture, energy, tourism, and cottage as well as small and medium industries so as to revive the economy affected by COVID-19. In this regard, provision for priority sector lending has been revised. Access to refinancing facilities has been decentralized. Concessional credit program has been restructured by widening the coverage.

1. Agriculture

Commercial banks will be required to invest at least 15 percent of their total credit in agriculture sector by mid-July 2023 so as to ensure food security and generate employment while becoming self-reliant on agriculture production. In addition, method of assessing compliance of agriculture credit will be revised.

With a view to promote self-reliance on major fruits, loan loss provision for credit on commercial farming of mango, orange, junar (sweet orange), mausam (sweet lime), kiwi, dragon fruit, lemon, litchi, avocado, among others, will be reduced to 0.2 percent for the first year and 0.6 percent for the second year.

Loan loss provision for credit on agriculture farming of silk, jute, cotton and other crops that help in establishing forward and backward linkages will be relaxed.

A provision for collateral of lease assets will be introduced to enhance credit to commercial agriculture, industry and other businesses through leasing or integrating land.

Agricultural Development Bank Limited (ADBL) will be promoted as the Lead Bank to facilitate credit in agriculture sector. This bank will be allowed to issue agricultural bond to ensure availability of long term financing in agriculture sector. This provision is expected to avail additional resources to agriculture sector and help the BFIs to comply with the regulatory requirement for agriculture credit by investing in agricultural bond.

The provision of agriculture credit swap among BFIs will be simplified further.

A provision of issuing Kisan (Farmer) Credit Card by ADBL will be introduced to ensure access to financial resources and agriculture information to farmers.

Institutional and infrastructural arrangements will be made to enhance agriculture training through the training centers of ADBL.

2. Energy sector
3. Tourism sector and micro, small and medium enterprises
4. Concessional loan
5. Miscellaneous

### Programs for economic recovery

The existing provision of refinance facilities has been revised with making a provision of extending refinance facilities upto 5 times the available fund so as to promote economic activities thereby providing concessional credit and enhancing access to credit for COVID-19 affected professions, enterprises and businesses.

Out of total refinance facilities, upto 20 percent can be extended based on customer evaluation while upto 70% through commercial banks, development banks and finance companies and upto 10% through the MFIs on lump sum basis.

Special refinance for the specified sectors including export and sick industry will be provided to the BFIs at 1%. Likewise, MSME refinance will be provided at 2% and general refinance will be provided at 3%. Borrowers have to pay 3%, 5% and 5% interest rates respectively on these loans.

### Credit Programs for COVID-19 affected Business/Profession

A provision will be made to provide 20 percent additional loan based on the working capital limit of mid-April 2020. BFIs can provide such loans based on borrower's need and feasibility of project/business so as to facilitate the continuation of business that are hard-hit by the COVID-19.

A provision will be made to provide loan from the BFIs at 5 percent for the operation and continuation of COVID-19 affected businesses including tourism and cottage, small and medium enterprises for payment of salaries to workers and employees of such sectors, and for providing opportunities to develop entrepreneurship to those who have lost jobs in the hard-hit sectors. The resources for this facility will be managed from the Rs. 50 billion fund that is to be established as mentioned in the GoN's budget for 2020/21.

### Critique

The highly anticipated monetary policy has addressed the revival of the COVID-19 affected economy by unveiling rescue packages. The policy inculcates a positive state of expectation for the pandemic-hit economy. It is in alignment with the annual budget, providing relief and rescue to businesses. The policy has been well received by the private sector as it addresses the key sectors for economic revival. The policy aims at easing liquidity and promoting stability and sustainable economic growth in the country.

The monetary policy prioritizes agriculture, energy, and small and medium-sized enterprises. For the first time in the history of monetary policy, the central bank has prioritized cottage and small industries. These crisis hit businesses been provided with relief packages and policies including the extension of loan repayment deadline, refinancing, and targeted lending.

The borrower-friendly monetary policy has addressed the needs of the business community by ensuring increased liquidity and easy access to credit. The policy largely mentions extension in loan repayment, grace period extension, and refinancing. The tourism sector that has been drastically affected by the pandemic is eligible for facilities announced under the recovery plan which include easy loans from BFIs, relief credit, and refinance.

Mergers and acquisitions have been promoted in the banking sector. The policy lays down some incentives to facilitate mergers. Likewise, the issuance of new licenses for microfinance companies has been forbidden in the overly saturated sector, which is commendable as it would ensure healthy competition and a controlled financial system in the nation.

The monetary policy has also relaxed the provisions regarding provisioning in case of loan extensions for the virus affected sector. This comes as a huge relief to the banking sector. The central bank has also opened doors for reviving a business through new investments by way of private equity funds, venture capital, debt-equity conversion, and special purpose vehicles. Overall, the monetary policy has introduced measures that are favorable to doing business despite the effect of pandemic and lockdown.

The policy aims to achieve an annual growth rate of 7 percent, which seems fairly unrealistic given the impact of the pandemic and the nation-wide lockdown. Moreover, the monetary policy has failed to address the need for an exit policy through a waiver of interest. It fails to consider that certain businesses are in no position to revive. The policy is also ambiguous regarding the amount of the refinancing package.

The policies and provisions laid out in the new monetary policy sound promising, but the real struggle would be its fast-tracked implementation. The policy looks good on paper, but the question regarding its implementation remains. To make the policy successful its implementation and careful monitoring of execution are equally important. Looking forward, the central bank should focus on speedy implementation of the monetary policy which will in return ensure economic revival and stability.
