# Business organization and environment

## Introduction

- A business is any organization set up to provide goods and/or services.
- Business aim to satisfy the needs and desires of their customers by selling a good or providing service.
- TO produce goods and services, a business needs to combine human, physical, financial, and entrepreneurial resources. These resources are referred to as the factors of production, combining land, labor, capital and enterprise:

1. Land: Natural resources used in the production process, e.g. wood, water, physical land, fish, water, metal ores and minerals.
2. Labor: Physical human effort and psychological intellect used in the production process.
3. Capital: Non-natural (manufactured) resources used to further the production process, e.g. tools, equipment, machinery, vehicles and buildings.
4. Enterprise: An individual with the necessary skills and ability to take risks in organizing the other factors of production to generate output in a profitable way.

- The production process adds value to the final goods and services sold to customers. Value added is the process of creating a product that is worth more than the cost of the inputs used to produce it, e.g. bottled orange juice is worth more than the original oranges grown on a farm.
- Businesses strive to add value to a good or service so that the product better meets the needs arid wants of their customers.
- Value added is measured as the difference between the cost of the inputs in the production process and the price of the final output.

## Main business functions and their roles

### Human resources

- Human resource management oversees staffing (personnel) within an organization.
- Human resource management (HR) issues such as recruitment, dismissal, training and development, redundancies, appraisals, performance management, career planning and the general welfare (well-being) of the firm's employees.
- The HR department must comply with employment legislation (labor laws), e.g. minimum wage legislation, regulations about working hours, equal opportunities law, and anti-discrimination acts.

### Finance and accounts

... continue from IB Diploma Business Management Study and Revision Guide.pdf (psc_preparation...)
