# Agriculture finance, credit, government support schemes and digitization

## Current state of agriculture

Nepal is an agro-based country, more than 60.0\% citizen of which still rely on the agriculture as major source of income. Even though majority of the citizens have occupation as farmer, many of them don't even possess their own land. Until 2006, agriculture itself held 39.5\% and of the total economy while looking into the GDP indicator. It stood at 32.5\% during 2014/15 and is currently 26.98\% of the GDP (2075/76).

The import of agriculture goods such as rice, vegetables and fruits have been increased significantly in recent years. The import of paddy/rice surged to Rs.25.0 billion in year 2014/15 which was Rs.17.26 billion in the previous year. Likewise the import of vegetables, fruits were accounted Rs.8.0 billion ad Rs.4.0 billion in year 2014/15. The ballooning import of agro products is one of the major components of widening trade deficit. Although the earthquake struck Nepal in the tenth month 2014/15, the impact on growth seems to be sizable; this is then estimated to have grown by only 3.0 \%. In 2015/16, a subpar monsoon will constrain agriculture growth, while the expected delay in getting reconstruction started, coupled with economic dislocation and damage to infrastructure, will curtail overall growth, including the agriculture sector in Nepal.

Despite direct contribution to domestic economy and the fact that more than 50% of country's export is attributable to agriculture, this sector has been a subject of lenient government overview and hence seeks a much focused intervention.

Several plans, programs, acts and regulations have been enacted and implemented by the government for the smooth development of agriculture sector in Nepal.

i. Agriculture Development Strategy/ ADS, 2015-2025 (It guides agriculture development in Nepal for coming two decades)
ii. Multi Sector Nutritional Plan and Food Security Action Plan (provides direction for achieving nutritional outcomes as envisioned by GoN)
iii. Zero Hunger Challenge Initiative 2025 (sets basis for ensuring that every man, woman and child enjoy their rights to get adequate food)
iv. Enacted 22 Policies (National Agriculture Policy 2004, Agribusiness Promotion Policy 2007, Agro Biodiversity Policy 2007, National Seed Policy 2000, National Fertilizer Policy 2002, Irrigation Policy 2003, National Tea Policy 2000, National Coffee Policy 2003, Dairy Development Policy 2007, Agriculture Perspective Plan 1995-2015, ADS 2015-2025, National Poultry Policy etc.) All these policies have clearly defined the ways to promote the respective sectors of agriculture and livestock.
v. Enacted 18 Acts (Seed Act, Pesticide Act, Plant Protection Act, Co-operative Act, National Tea and Coffee Development Board Act 2048, National Cooperative Development Board Act 2049, Nepal Agriculture Research Council Act 2048 etc.)
vi.	 Enacted 9 Regulations (Food Regulation 2041, Seed regulation 2054, Cooperative Regulation 2049 etc.)
vii. Enacted 7 Orders (Chemical Fertilizer Control Order 2055, Bird Flu Control Order, 2064, etc.)
viii. Implemented smart subsidy policies like subsidy on fertilizer, seed, agriculture inputs, crop and livestock insurance, etc.
ix. Youth focused programs for reducing youth migration and increasing contribution from women at household level.
x. Demand based programs like small irrigation, cooperative farming, farmily farming, marketing structures, etc.
xi. Problem based research and development activities, like Farmer's Field Demonstration, Integrated Pest Management and participatory research, etc.
xii. Food quality control like good manufacturing practices, joint monitoring, green strikers, etc.
xiii. Value chain support grants assisted by IFAD, ADB, World Bank, USAID, PACT, HVAP, UNNATI, KUBK, RISMFP, HIMALI, AFSP, etc.
xiv. Prime-minister Agriculture Modernization Project (10 year program envisioning enhanced production, productivity, commercialization and mechanization of agriculture)

Despite all these measures and prowess by government, private and international spheres to empower agriculture, the backbone of economy is still a problem ridden sector.

- Due to the lack of vocational training and credit facilitation farmers are reluctant to transition to commercial and mechanistic methods of cultivation.
- Brain drain/migration of youths/this sector is almost in the hand of elderly, children and women
- Difficult topography/terrain to extend agricultural technology, credit, extension and material support
- Subsistence type of farming (0.8 ha land/family)
- Fallowing of land by large farmers
- Land fragmentation/ haphazard land plotting practices
- Unequal land distribution/dual land ownership
- Of the total 2,265,000 hectares of irrigable land, only 1.473 million hectares are irrigated (including all forms of irrigation supply) by the end of the FY 2018/19. Among irrigable fraction of land, only 33% of all has access to year-round irrigation.
- Problem in agriculture product marketing/syndication/high interference of agents/mediators
- Stereotypically, sector is recognized as undignified job by the society
- Poor road/transportation networks
- Lack of large processing industries/warehouses/godowns/cold storages. Orchards of Humla and Jumla are inaccessible for the people of Kathmandu due to no proper transportation facility, resulting in post-harvest deterioration of those valuable products.
- Agriculture products are expensive and less competitive as compared to Indian products due to lack of government subsidies
- Neither commercial banks are serious in investing in this sector nor rural cooperatives are focused on agricultural credit
- Haphazard use of chemical fertilizers and pesticides thereby causing serious health hazards
- Decreasing soil fertility and productivity, etc.

Several aspects of macro-economic and budgetary policy that are integral to shape and provide direction to agriculture require reconsidered and reformation. Government priority sector has to be reigned by agriculture instead of other vague and less important sectors.

### Scope of agriculture 

- Ever increasing population and asynchronous expansion of cultivable land (human has to take food not money)
- Rich in bio-diversity, different kinds of ecological zones (high hills, hills, plain etc.)
- Changing food habit of people, increasing tourist flow
- Decreasing production
- Improved technology available
- Youths particularly returnee from third countries are attracted in agriculture sector
- Many GOs, Semi GOs, NGOs, INGOs and Bi-lateral organizations are investing and promoting agriculture sector
- No problem of market/demand of organic products is high
- High agriculture trade deficit opens the door to invest in this sector
- Rules of government and NRB to invest in this sector (for BFIs 10% of total outstanding loan)
- Govt. is planning to provide identity/ pension card to farmers
- High profit margin if market is managed properly

## Agriculture Finance

The contribution of agriculture to the GDP was more than 62.0% before 1980s. It was more than 90.0% before 1956 A.D, at the time when Nepal Rastra Bank was established as the central bank of Nepal. In the decade of 1990s, it declined to 51.0% and it went on further declining to 40.0% in 2000 A.D. Since then, it has been contracting, standing at around 33.0% in 2015. Much of the richer history in the early days was partly due to the expansion of industry and service sectors and partly as a result of the disincentives created by macroeconomic environment in agriculture.

Similarly, the growth rate of agricultural productivity exhibited a downward trend at that time. Thus, agricultural productivity stagnated at a time when the population growth rate was around 2.5% per year. This period also witnessed a slow growth due to lack of coherent policies in agriculture credit. As a result, a sharp decline in export of cash crop production, with only marginal increase of food production that could not even meet the demand of the alarming increase in population was witnessed. Hence, domestic food supply had to be augmented through large imports. Despite all these, agriculture remained a vital pursuit in Nepal. Unfortunately, agricultural financing has suffered a major setback. The factors contributing include low agricultural productivity, lack of capital and credit facilities, inadequate availability of inputs and storage facilities, lack of conducive and enabling environment, weak agricultural extension delivery and outdated infrastructure. Based on the inhibiting factors above, there is the need to recruit more financial resource to enhance production and boost productivity in Nepalese agriculture sector through investment in modern technology.

Agricultural operations in Nepal over the past years have been quite primitive and productivity have remained very low due to inadequacy in use of modern technology. The cost of agricultural machinery like tractors, harvesters, planters, etc., are astronomically high, relative to conventionally used production inputs, and are out of reach of an average Nepalese farmer. Also included is inadequate supply of critical inputs such as hybrid seeds, fertilizers and agro-chemicals at the appropriate time and at affordable prices.

The Nepal government has been intervening in the agricultural sector through its policies, programs and strategies to increase production and strengthen the sector so as to play its expected role in the development process but such efforts have not been fruitful despite the size of resources committed. Various work have been carried out to increase the agriculture productivity, economic growth and wealth creation. However, despite that, productivity has remained low at times when necessity to ensure sound flow of capital finance in the form of money and other agricultural facilities have been overlooked.

Agricultural finance generally means studying, examining and analyzing the financial aspects pertaining to farm business, which is the core sector of Nepal. The financial aspects include money matters relating to production of agricultural products and their disposal. Agricultural finance can be dealt at both micro level and macro level. Macro-finance deals with different sources of raising funds for agriculture as a whole in the economy. It is also concerned with the lending procedure, rules, regulations, monitoring and controlling of different agricultural credit institutions. Hence macro-finance is related to financing of agriculture at aggregate level. Micro-finance refers to financial management of the individual farm business units. And it is concerned with the study as to how the individual farmer considers various sources of credit, quantum of credit to be borrowed from each source and how he/she allocates the same among the alternative uses within the farm. It is also concerned with the future use of funds. Therefore, macro-finance deals with the aspects relating to total credit needs of the agricultural sector, the terms and conditions under which the credit is available and the method of use of total credit for the development of agriculture, while micro-finance refers to the financial management of individual farm business.

### Significance of Agricultural Finance

- Agriculture finance assumes vital and significant importance in the agro–socioeconomic development of the country both at macro and micro level.
- It is playing a catalytic role in strengthening the farm business and augmenting the productivity of scarce resources. When newly developed potential seeds are combined with purchased inputs like fertilizers and plant protection chemicals in appropriate/requisite proportions will result in higher productivity.
- Use of new technological inputs purchased through farm finance helps to increase the agricultural productivity.
- Accretion to in farm assets and farm supporting infrastructure provided by large scale financial investment activities results in increased farm income levels leading to increased standard of living of rural masses.
- Farm finance can also reduce the regional economic imbalances and is equally good at reducing the inter-farm asset and wealth variations.
- Farm finance is like a lever with both forward and backward linkages to the economic development at micro and macro level.
- As agriculture is still traditional and subsistence in nature, agricultural finance is needed to create the supporting infrastructure for adoption of new technology.
- Massive investment is needed to carry out major and minor irrigation projects, rural electrification, installation of fertilizer and pesticide plants, execution of agricultural promotional programmes and poverty alleviation programmes in the country

### Agricultural Credit Market, Need, Types and Sources

Agriculture sector is the mainstay of the economy of Nepal and it accounts for one third of GDP. It employs large population directly engaged in agriculture but it contributes low export earnings and as a result of this import has been surged in the last decades and making alarming trade deficit with huge expenses of foreign exchange reserve for financing the imports. Though, agriculture is an important large market and industry, yet it is far away from the availability of financial resources. Agricultural credit is linked with growth of agriculture, whereas rural finance covers all the aspects of socio-economic life of rural area. It covers a wide variety of farm and non-farm productive activities such as agriculture, animal husbandry, fisheries, forestry, small agro-based industries as well as development of physical and social infrastructure in the form of transport and communication, water and power, education and health. Credit is required in every type of business and agriculture is not exception of it. The need for agriculture credit becomes more important when it moves from traditional subsistence to modern commercialization. The agriculture sector at present is based with number of handicaps. The land holding is very small. The population is growing at a faster rate. Agricultural labor is often under-employed. Production suffers from weather risks. The capacity of farmers to save and invest is very low. The agricultural productivity is low due to low use of inputs. The farmers therefore, need credit to increase productivity and efficiency in agriculture. This need is increasing over the years with the rise in use of fertilizers, mechanization and rise in prices. Briefly the need for agricultural credit can be summed up as follows;

- Purchase of new inputs
- Purchase of implements
- Better management of risk
- Permanent improvement in land
- Better marketing of crops
- Facing crises
- Balanced development

#### Types of agriculture credit

**Short Term Credit**: The short term credit ranges up to one year. The farmers need short term credit for meeting the working capital arrangements of agriculture. For instance, they need short term credit for the purchase of seeds, fertilizers, pesticides, bullocks and other casual expenses. Sometimes short term credits are also raised for paying rents, revenue and also meeting the financial requirements of the family. The short term credit is repaid after marketing the product of next crop.

**Medium Term Credit**: The medium term loan extends from 1 to 5 years. The farmers require medium term credit for the purchase of cattle, purchase of implements, improvements in water courses etc. The loan is obtained on the security of movable and implements.

**Long Term Credit**: The duration of long term credit exceeds five years. The farmers need long term credit for making improvements of permanent nature in land such as sinking of tube wells, reclamation of land, building, purchase of machinery and implements etc.

#### Sources of agriculture credit

**Non-Institutional Sources/ Informal Sources**: The major non-institutional sources of farm credit in Nepal are money lenders, friends, relatives, shopkeepers and commission agents. The lenders of the informal sources (friends, relatives etc) have certain advantages over the formal credit sources. The informal lenders usually know the borrowers personally. They require little security for advancing loans. The loans are given for consumption as well as production purposes. The lenders are approachable at all times. They are also lenient in rescheduling loans. However, informal lenders are also accused of charging higher rates of interest. They extract monopoly profits from the borrowers.

**Institutional Sources/ Formal Sources**: The institutional and formal sources are the banks and financial institutions mostly regulated by the central of Nepal (Nepal Rastra Bank) in Nepal. Moreover, the cooperatives and other formal sources of financial institutions and saving and credit cooperatives have been also engaged in agricultural financing in Nepal with a very limited capacity, quantity and volume both in rural and urban areas. The formal source, especially the BFIs in Nepal as per the regulation issued by the NRB provides agriculture credit for

1. Development loans
2. Production loans
3. Agri-business loans
4. Cottage industry loans and
5. Off farm income to farmers generating activities loans

### Reasons for low agriculture credit flow in Nepal

- Farmers cannot provide good collaterals to BFIs
- Ineffective insurance policies/lack of its knowledge to farmers
- Administrative obstacles to get loan/ different types of documents needed
- Ignorance of youths towards agriculture sector
- Lack of availability of agricultural inputs at right time, right place and affordable price
- Monsoon based agriculture/risky business
- High cost of production
- Uncertainty of market demand and high volatility in commodity price due to open border economy. 
- Land fragmentation/lack of farm mechanization
- Repetition of credit facilitation to same farmer from Banks, cooperative, FIs, NGOs, etc. thereby creating an unfair environment for investment.

### Efforts of NRB in managing credit in Agriculture

Agriculture Development Bank (ADB) and other BFIs were authorized by NRB to establish and to provide the financial services along with others, and to extend the agricultural credit. The latter, however, mostly remained reluctant in financing agriculture despite numbers of BFIs reached more than 200 with around 4000 branch network in various geographical areas in Nepal. Although, the BFIs, since then, are providing loans to the farmers for meeting their short and medium term requirements, this has not been sufficient. It is negligible both in percentage and volume of total loan extended by them. The agricultural loans are advanced to the farmers against the security of land, crops, and fixed assets and even on personal security and BFIs disburse agricultural credits for the purchase of inputs, cattle, tractors, dairy farming, installation of tube wells etc. In Nepal BFIs provide loans under the regulated credit scheme of NRB and outside of this scheme. In addition to the BFIs regulated by the NRB, cooperatives are oldest institutional sources of agriculture credit in Nepal but their performance in the spread and utilization of credit to the small farmers is not satisfactory. NRB has made the following efforts since its establishment for the development of agricultural sector and credit to agriculture.

- Establishment of Agriculture Development Bank (2024)
- Directed Credit Program (2031)
- Micro Credits for woman, Third Animal Husbandry Program, Western Poverty Alleviation Program and other targeted credit program in different times in various geographical reasons of Nepal.
- Deprived Sector Lending Requirement to BFIs. At present BFIs of A, B and C class should provide minimum of 5.0, 4.5 and 4.0 percent loan in the specified deprived sector.
- Liberal Licensing policy of opening BFIs for making access of rural credit.
- Establishment of Co-operatives with limited banking facilities in the past decade.
- Establishment of Rural Self Reliant Fund and financing for agriculture groups through cooperatives.
- Mandatory regulation for BFIs to disburse minimum of 20.0 percent of total loan to the Productive Sector and of which at least 12.0 percent to agriculture and energy sector. Likewise, both B and C class BFIs made mandatory to disburse minimum of 15.0 and 10.0 percent of total loan in the productive sector by mid-July 2016.
- Refinance facility at 4.0% for the loans that have been disbursed to agriculture, fishery, and poultry and among others.
- Easy refinance loan provision at 1.0 percent for the agriculture and small business based income generating activities in poverty stricken areas and the districts which have high density of poverty.
- Agriculture loan at 6.0 percent to the youths and 4.0 percent subsidy in interest.
- Provision of providing loan in to commercial agriculture, small and medium enterprises and the income generating activities in earthquake stricken areas up to 1.0 million against the collateral without access of motor able road.

### Status and Constraints

In Nepal the loans extended by the BFIs are mostly utilized by big farmers in the name of small farmers but in fact those are not in agriculture business. Nepalese banking sector comprises set-ups enlisted in Table \ref{tab:disaggregated-status-institutions-in-nepal}. Likewise, there are 16 cooperatives and 31 NGOs that are licensed by NRB (as of Dec, 2015). Financial Institutions collects the scattered deposit from the surplus sector and mobilizes for the capital formation in the productive sector and thereby support economic growth. The deposit mobilization and credit disbursement stood Rs.1872 billion and Rs.1440 billion respectively as on mid-Dec 2015. Agriculture loan (including fishery) provided by BFIs reached to Rs. 66.5billion and stood 4.6 percentages in the six months of 2015/16. While the same with addition to agriculture, fishery and production related stood at 23.3 percent in mid-Jan 2016 and the deprived sector loan stood at 4.9 percent in the same period. These facts shows that, despite mandatory requirements in agriculture credit financing, BFIs have rather opted to pay penalty rather than extend loans in the agriculture sector. Despite various effort made by the central bank of Nepal for increasing agricultural credit and expansion of financial services in the rural areas for access and inclusion, BFIs still remain reluctant to extend the loan in the targeted areas. Some progress in this matter has been achieved in the past few years along with the announcement of mandatory productive sector credit policy and deprived sector credit policy.

Recently, NRB has established a fund scheme called Deposit and Credit Guarantee Fund (DCGF) for providing credit guarantee services for priority sector as well as for livestock, vegetable farming, foreign employment, micro and deprived sector, and small and medium-scale enterprises^[Annual Report, 2018/19, NRB]. The DCGF guaranteed total credit amounting to Rs. 25.66 billion and total deposits amounting to Rs. 603.39 billion as of mid-July 2019.

Another such fund initiative established by concerted efforts from GoN and NRB is Rural Self-Reliance Fund (RSRF), established in 1991 in order to raise the socio-economic status of economically weak and poor citizens residing in rural areas through the provision of low interest credit. RSRF established with the seed capital of Rs. 10 million and has reached Rs. 0.79 billion with the contribution of

  - Rs. 0.54 billion from GoN and
  - Rs. 0.25 billion from NRB.

In the context of changing circumstances, with an objective of expanding the investment coverage and updating the RSRF in line with its objective, the Rural Self-Reliance Fund Operations Directive, 2017 has been prepared and brought into implementation since 23 April 2018.

Since its establishment, Micro-finance Promotion & Supervision Department of NRB has been operating this fund. Following the cabinet decision of GON dated 10 December 2018 that granted the letter of consent to transfer the ownership of RSRF program to Small Farmers Development Microfinance Financial Institution Ltd., the GON (ministerial-level decision) approved the RSRF Manual, 2019 on 11 March 2019. As per the section 18 of the Manual, tripartite agreement for the handover of the fund was completed on 16 July 2019 and loan files were transferred.

The RSRF has been providing loan to affiliate institutions on installment basis not exceeding 10 times of their core capital (viz., share capital, general reserve, and profit) on first, second and third loans. The first, second and third installment of loans are capped at Rs 3 million, Rs.3.5 million and Rs. 4 million respectively. Arrangement has been made to provide micro-credit through cooperatives to its member up to Rs.125000 for improving the economic/social status of the deprived sector. Since 2002/03, the fund had provided wholesale credit to Agricultural Development Bank Limited (ADBL) for the purpose of arranging long-term capital especially required for businesses like tea, black cardamom and cold storage in the past. At present, the RSRF does not provide such long term credit.

As of mid-July 2019, the outreach of RSRF has expanded to 72 districts. The RSRF disbursed loan amounting to Rs. 2.53 billion to 1239 institutions comprising of 1135 cooperatives, 53 NGOs and Agricultural Development Bank. Of the total disbursed amount, Rs.2.19 billion was repaid (with 95 percent of repayment rate) while Rs.0.33 billion remained as outstanding. As of mid-July 2019, total households benefiting from this fund has reached 63,396.

Despite all these arrangements, reasons for low credit flow to agriculture sector in Nepal can be analyzed in the following two ways:

**1. Supply Side Constraints**

- BFIs are not encouraging to disburse agriculture credit as such type of loan is small in size and high administrative cost which may not earn more profit.
- Generally the BFIs require the sound collateral back up to provide the loan. Most of the farmers have not enough property that can be mortgaged to get the loan.
- There is high risk of being low production of crops due to unfavorable climate. Likewise different the influential type of diseases are making the poultry business vulnerable.
- Insurance could be one of the factors to mitigate such type of risk, however, the insurance companies are yet to be expanded their businesses to the agriculture sector.
- No regular cash flow of farmers to repay the monthly installment.
- No mechanization and modernization in agriculture sector so that the loan could be provided against the backup of the machines and the project itself.
- BFIs's network is concentrated in urban areas, the presence of BIFs with wide range of affordable services in the rural areas are not satisfactory.

**2. Demand Side Constraints**

- Lengthy administrative procedure of BFIs, long and complex application form which is beyond the understanding of most of the farmers.
- Poor banking habit, wrong perception about availing the bank credit. Still many people perceive that taking loan from bank diminishes the prestige in the society.
- Lack of financial literacy, less awareness about the services, products, procedure, cost and among others.

### Efforts from Government of Nepal

One of the major policy instruments for mobilizing financial resources to enhance agricultural productivity is the use of government subsidy in all over the world. The Nepalese government has granted selective subsidies on farm inputs, farm equipment and facilities and farm service to reduce the cost of agricultural production mostly before the economic liberalization in 1980s. The subsidy policy embarked upon by the Nepalese government cuts across the various sub-sectors of the agricultural sector. In the crop sub-sector, input covered by subsidy are seeds, seedling, water supply, fertilizer, pesticides, herbicides, processing and storage equipment and irrigation facilities such as dams, and boreholes, construction pumps, sprayers and other farm machinery and equipment. In addition to the role of the governments, the local government authorities are expected to take over progressively the responsibilities of the state with respect to provision of rural infrastructure and promotion of rural infrastructure and promotion of farmers organizations, mobilization of farmers for accelerated agricultural and rural development through cooperative societies, provision of land for new entrants into farming in accordance with the provision of the land reform policies of different times. The role of the private sector in resource mobilization towards agricultural financing is to take the advantage of the improved enabling environment provided by the public sector for profitable investment in agriculture. In particular, the private sector is expected to participate in the maintenance of small and medium scale agriculture projects for the purpose of maximizing agriculture productivity. Government has prioritized agriculture sector since the first development plan. Subsequently following policies were implemented to increase the productivity and flow of financial resources in agriculture sector in Nepal over the years by the government of Nepal.

- Agriculture sector has been kept in priority in Plans and Programs but never prioritized the actions and budget since the inception of planning in 1956 A.D.
- Government of Nepal has imposed 20 years Agriculture Strategy (1994/95 to 2014/15) which emphasized the modernization and commercialization of agriculture.
- 13th development plan has envisioned to achieve growth of 4.5% in agriculture sector during the plan period.
- Agriculture Development Strategy (ADS) 2014 has been made public recently with the vision of "Self reliant, sustainable, competitive and inclusive agricultural sector that drives economic growth and contributes to improved likelihood and food and nutrition securities" and the growth target has been set at 6percent in the coming 10 years.
- Various programs have been announced in budget for modernization, commercialization and competitive agriculture sector.

### Way Forward and Role of Central Bank for Agricultural Credit

NRB is playing an active role of improving the quantitative and qualitative targets of agriculture credit. Although, the bank did not have specific and clear mandate for the development of agriculture sector that allow the bank to play some major role in agricultural financing to advance credit to agriculture and support for economic growth and development of nation. In the past the bank had established a separate Division for agricultural credit for research, assessment of credit needs and supervision of rural credit operations but now it has been restructured with the Micro Finance Promotion and Supervision Department. In future, NRB can establish a separate Desk/Division for the regulation and supervision of agriculture credit as well as for other productive sector credit programs. Bank Financing in the form of capital investment can generate increased productivity in agriculture sector by fulfilling the financing need of the farmers to get the agriculture inputs such as fertilizers, machines, irrigation, quality seeds, consultation service, and improved technologies and among others. The greater and wider level of financial access and inclusion can support to meet the demand of agriculture credit from the supply side improvement. As per the agriculture census 2011, only 22.0 percent farmers use bank loan and 42.0% farmers have bank financing need. As the agriculture credit tend to be small in size in comparison to other credit products, there is a lack of incentive on part of banks considering high administrative costs and low revenue outcomes. However, there is less possibility of default. Various numbers of loan accounts ultimately create good earning in the long term. Not only in the form of profitability point of view, is agriculture credit considered good from the financial stability point of view too. The focus of NRB should be in the areas on which, generally banks have the internal policy of payback the interest and principal in monthly basis. Agriculture sector can not generate earning in monthly basis. So repayment cycle should be developed as per their harvesting time and good quality infrastructure reduces cost of production, distribution and also eases to get the agriculture inputs on time.

Moreover, NRB needs to promote BFIs lending on agriculture sector infrastructure to improve the quality of rural and agricultural road network, support for small and medium size electricity generating projects for supplying power to the agriculture. Financing for mechanization of agriculture might also be another avenue to increase agriculture productivity and credit to agriculture. As per the latest survey on Agriculture Mechanization 2012 (CBS), only one percent farmers have tractor or power tiller, and thresher, 52.0 percent farmers have traditional equipment like wooden plough. Banks should finance for the machinery and equipment in the back of the machinery itself. Financing in irrigation project can directly benefit the farmers. Irrigated land out of total arable land in only 54.4 percent as per NLSS III. NRB should also focus to make financial literacy program more effective and simplified the loan taking procedure from BFIs, especially for the purpose of agriculture credit.

- Likewise, joint efforts and national campaign program about agriculture credit and proactive and dynamic revision in related policies and regulations relating to agriculture credit is the requirement of this time to increase the agriculture credit in Nepal. 
- The uncertainly elements in agriculture be minimized. The farmers must be hardworking so that they could utilize the farms efficiently. As a result, the agriculture production increases and agriculture sector will become profitable in this way; the flow of agriculture credit will go up. Financial literacy needs to reach up to farmers for this reason.
- The provision of agriculture loans to be aligned with productive capacity and efficiency of land, rather securities. Industrial and commercial loan to be embedded with agriculture sector commercialization in this sense.
- The farmers to be provided with complete package of agriculture inputs instead of just loans as the case of supervised credit. Therefore, this scheme should be effectively implemented. Targeted credit programs are needed for different agriculture inputs for this reason.
- The better advisory services are provided regarding agriculture marketing. In this way, the farmers could be able to get fair prices of their produce and easily repay loans. Agriculture advisory services and technical areas of agriculture needed to get access for agriculture credit to support farmers.
- A revolution in agriculture sector is brought about so that people could pay more attention on developmental works, rather social traditions. A better institutional set up is required for policies, programs and assessment of credit availability.
- Commercial banks even the cooperatives are not prepared to give loans to farmers. Thus because of poor financial status, more affects of natural uncertainty in agriculture, the commercial banks and other financial institutions are not prepared to lend to farmers. They think that the cost of advancing loans to farmers is more than their revenues. The relation which existed between banks and industry and commerce is missing in case of banks and farmers. The farmer who is poor and illiterate cannot frequently visit the banks as the businessmen do. Thus, these constraints and problems needs to be addressed by the NRB through appropriate policy.
- Lack of securities is another problem repeatedly raised by BFIs in agricultural credit. Securities and collateral for the agricultural loan need to be revisit and require making a separate guidelines or directives for agriculture credit.
- Non-institutional credit is a major problem. As so many farmers in Nepal do not have any way out except to go for non-institutional credit. But the friends and relatives are limited source; they fail to supply enough funds. They could not provide loans for consumption and limited production purposes. They hardly provide developmental loans. Then, the farmers move to landlords and commission agents to get the loans. The landlords provide loans to marginal extent and exploit the farmers. Hence, access and delivery of financial service in the required area needs to be set up to solve this problem.
- Improper use of agriculture credits has not been controlled as so many experts are of view that agriculture credit will be least beneficial if they fail to increase the agriculture output, increase the cultivable area and improve the lot of farmers. Monitoring and supervision of such credit should be strengthened.
- Complicated procedure and strict conditions of BFIs is major hurdle to take loans in Nepal. The farmers have to face very strict conditions and complicated procedures while getting the loans. Again, the official formalities and, the behaviors of bank obstruct the small farmers to get loans. Similarly, the weak financial position and higher interest rate also hamper loaning farmers. Process and procedure on credit policy for agriculture and interest rate rules in agriculture require to be more simplified and better regulated to solve this problem.
- For BFIs point of view recovery of agriculture credit might deteriorate their assets quality and reduce the profitability. The process of recovery of loans is very much low. Due to financial position the small farmers fail to pay back the loans. The process of loan recovery limited, as the farmers hardly care for repayment of loans. Refinance facilities in agriculture credit needs to be strengthened.

## Credit and finance management system

- CPAS software
- Credit administration (CAD) related services
