# Banking and finance regulation and relevent essays

## Money laundering

Money laundering is the process by which the person attempt to hide and disguise the true origin and ownership of the proceeds of their unlawful activities. The term is also used in relation to the financing of terrorist activity (where the funds may, or may not, originate from crime). Financing of Terrorism means providing financial support to any form of terrorism or to those who encourage terrorism. Money laundering, in essence, means 'making dirty money look clean'. The modern term of Money laundering was first used in a legal context in 1982 in America relating to the confiscation of laundered Columbian drug proceeds. However, historically, the concept of money laundering was originally used by the American enforcement officers in the 1920s.

The legalization of illegal proceeds is significant as it represents the common component in regard to the various definitions of money laundering. Thus, the aim of money laundering is to cover up the predicate offenses from which proceeds are derived and to ensure that the criminals can enjoy their proceeds, by conserving or investing them in the legal economy.
